SRC_FILES=	bitimage.c \
		bspimd.c \
		fbf.c \
		imd.c \
		imdload.c \
		ivi.c \
		pcx.c \
		pieblitfunc.c \
		pieclip.c \
		piedraw.c \
		piefunc.c \
		piematrix.c \
		piemode.c \
		piepalette.c \
		piestate.c \
		pietexture.c \
		rendfunc.c \
		rendmode.c \
		screen.c \
		tex.c \
		textdraw.c

LIBS=framework gamelib

LIB=ivis_opengl

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

