top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

CPPFLAGS := $(CPPFLAGS) -I$(top_srcdir)/lib/ivis_opengl

SRC= \
	sequence.c \
	timer.c

LIB=sequence

include $(top_srcdir)/makerules/lib.mk
