top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

CPPFLAGS := $(CPPFLAGS) -I$(top_srcdir)/lib/ivis_opengl

SRC= \
	GLee.c \
	ivi.c \
	pieblitfunc.c \
	piedraw.c \
	piefunc.c \
	piematrix.c \
	piemode.c \
	piepalette.c \
	piestate.c \
	rendmode.c \
	screen.c \
	tex.c \
	textdraw.c

LIB=ivis_opengl

include $(top_srcdir)/makerules/lib.mk
