top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

CPPFLAGS := $(CPPFLAGS) -I$(top_srcdir)/lib/ivis_opengl

SRC= \
	bitimage.cpp \
	imd.cpp \
	imdload.cpp \
	jpeg_encoder.cpp \
	pieclip.cpp \
	png_util.cpp \
	GLee.c \
	ivi.cpp \
	pieblitfunc.cpp \
	piedraw.cpp \
	piefunc.cpp \
	piematrix.cpp \
	piemode.cpp \
	piepalette.cpp \
	piestate.cpp \
	rendmode.cpp \
	screen.cpp \
	tex.cpp \
	textdraw.cpp

LIB=ivis_opengl

include $(top_srcdir)/makerules/lib.mk
