SRC_FILES= \
		bspimd.c \
		ivi.c \
		pieblitfunc.c \
		piedraw.c \
		piefunc.c \
		piematrix.c \
		piemode.c \
		piepalette.c \
		piestate.c \
		pietexture.c \
		rendfunc.c \
		rendmode.c \
		screen.c \
		tex.c \
		textdraw.c

LIBS=ivis_common framework gamelib

LIB=ivis_opengl

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

