include $(abs_top_srcdir)/makerules/configure.mk

SETUPFILE=$(PACKAGE)-$(PACKAGE_VERSION).exe

all:
ifdef INSTALLER
all: $(SETUPFILE)
endif

$(SETUPFILE): $(srcdir)/warzone2100.nsi $(abs_top_builddir)/src/warzone2100.exe $(abs_top_builddir)/data/base.wz $(abs_top_builddir)/data/mp.wz $(abs_top_builddir)/data/mods/global/grim.wz
	$(MAKENSIS) -DPACKAGE="$(PACKAGE)" -DPACKAGE_NAME="$(PACKAGE_NAME)" -DPACKAGE_VERSION="$(PACKAGE_VERSION)" -DPACKAGE_BUGREPORT="$(PACKAGE_BUGREPORT)" -DVERSIONNUM="$(INSTALLER_VERSION)" -DEXTDIR="$(DEVDIR)\bin" -DLOCALEDIR=$(LOCALEDIR) $<

clean:
	$(RM_F) $(SETUPFILE)
