MAKERULES=../makerules
include $(MAKERULES)/configure.mk

SETUPFILE=warzone2100-$(VERSION).exe

all:
ifdef INSTALLER
ifeq ($(strip $(PLATFORM)),windows)
all: $(SETUPFILE)
endif
endif

$(SETUPFILE): warzone2100.nsi ../src/warzone2100.exe ../data/warzone.wz ../data/mp.wz ../data/mods/global/grim.wz
	$(MAKENSIS) -DPACKAGE="$(PACKAGE)" -DPACKAGE_NAME="$(PACKAGE_NAME)" -DPACKAGE_VERSION="$(VERSION)" -DPACKAGE_BUGREPORT="$(PACKAGE_BUGREPORT)" -DVERSIONNUM="$(INSTALLER_VERSION)" -DEXTDIR="$(DEVDIR)\bin" -DLOCALEDIR=$(LOCALEDIR) $<

clean:
	$(RMF) $(SETUPFILE)
