# CirrusCI - test builds on FreeBSD instances
# See: https://cirrus-ci.org; https://cirrus-ci.org/guide/FreeBSD/

freebsd_build_task:
  only_if: $CIRRUS_PR != '' || $CIRRUS_BRANCH !=~ 'l10n_.*'

  freebsd_instance:
    # See the list of available FreeBSD image families here: https://cirrus-ci.org/guide/FreeBSD/
    matrix:
      - image_family: freebsd-12-2 # FreeBSD 12.2-RELEASE
      - image_family: freebsd-11-4 # FreeBSD 11.4-RELEASE
#    cpu: 4
#    memory: 8G

  install_script:
    - pkg update -f
    - pkg clean -a
    - pkg install -y git cmake ninja p7zip gettext pkgconf png sdl2 openal-soft physfs libvorbis libtheora freetype2 harfbuzz curl libsodium sqlite3 rubygem-asciidoctor

  init_git_submodules_script: git submodule update --init --recursive

#  configure_debug_script: cmake '-H.' -Bbuild/debug -DCMAKE_BUILD_TYPE=Debug -G"Ninja"
#  build_debug_script: cmake --build build/debug
#  clear_debug_build_script: rm -rf build/debug

  configure_release_script: cmake '-H.' -Bbuild/release -DCMAKE_BUILD_TYPE=RelWithDebInfo -G"Ninja"
  build_release_script: cmake --build build/release


# # CirrusCI - test builds on macOS VMs
# # See: https://cirrus-ci.org; https://cirrus-ci.org/guide/macOS/
#
# macos_build_task:
#
#   osx_instance:
#     # See the list of available macOS images here: https://cirrus-ci.org/guide/macOS/
#     matrix:
#       image: high-sierra-xcode-9.4.1
#       image: mojave-xcode-10.1
#
#   env:
#     MACOSX_DEPLOYMENT_TARGET: 10.10
#
#   install_script:
#     - brew install cmake
#     - brew install gettext
#     # NOTE: Specify an explicit Asciidoctor version to help ensure reproducible builds
#     - sudo gem install asciidoctor -v 2.0.12 --no-document
#     # gcc6+ is currently required to bootstrap vcpkg on macOS
#     - brew install gcc@7
#     - sudo bundle install --gemfile="macosx/BuildBot/Gemfile"
#
#   init_git_submodules_script: git submodule update --init --recursive
#
#   build_script:
#     - source .ci/travis/export_build_output_desc.sh
#     - macosx/BuildBot/travis_cmake_build.sh "${WZ_BUILD_DESC_PREFIX}-" "tmp/wz_upload"
