# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en"
early_access: false
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  poem: false
  review_status: false
  collapse_walkthrough: true
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  pre_merge_checks:
    docstrings:
      mode: 'off'
  auto_review:
    enabled: false
    drafts: false
chat:
  allow_non_org_members: false
  auto_reply: false
