# WZ2100 Azure build pipeline
#
# Currently contains:
#  - macOS builds

trigger:
  branches:
    include:
    - '*'
    - refs/tags/*
    exclude:
    - l10n_*

jobs:
#- template: .ci/azure/templates/macos-build-pipeline-template.yml
#  parameters:
#    name: macOS_Xcode_9_4_1
#    displayName: 'macOS [Xcode 9.4.1, macOS 10.13 SDK]'  # friendly name to display in the UI
#    vmImage: 'macOS-10.14'
#    xcodeDeveloperDir: '/Applications/Xcode_9.4.1.app/Contents/Developer'
#    vcpkgBuildXcodeDeveloperDir: '/Applications/Xcode_10.3.app/Contents/Developer'
#    vcpkgInstallXcodeDeveloperDir: '/Applications/Xcode_10.3.app/Contents/Developer'
#    publishArtifact: false
- template: .ci/azure/templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_Xcode_10_3_novideos
    displayName: 'macOS [Xcode 10.3, macOS 10.14 SDK] - no videos'  # friendly name to display in the UI
    vmImage: 'macOS-10.14'
    xcodeDeveloperDir: '/Applications/Xcode_10.3.app/Contents/Developer' # Set default Xcode to Xcode 10.3 on macOS 10.14
    vcpkgBuildXcodeDeveloperDir: '/Applications/Xcode_11.7.app/Contents/Developer'
    includeVideos: false
    publishArtifact: true
    artifact: 'warzone2100_macOS_novideos'
# - template: .ci/azure/templates/macos-build-pipeline-template.yml
#   parameters:
#     name: macOS_Xcode_10_3
#     displayName: 'macOS [Xcode 10.3, macOS 10.14 SDK] - full'  # friendly name to display in the UI
#     vmImage: 'macOS-10.14'
#     xcodeDeveloperDir: '/Applications/Xcode_10.3.app/Contents/Developer' # Set default Xcode to Xcode 10.3 on macOS 10.14
#     vcpkgBuildXcodeDeveloperDir: '/Applications/Xcode_11.7.app/Contents/Developer'
#     includeVideos: true
#     publishArtifact: true
#     artifact: 'warzone2100_macOS'
# - template: .ci/azure/templates/macos-build-pipeline-template.yml
#   parameters:
#     name: macOS_Xcode_11
#     displayName: 'macOS [Xcode 11.7, macOS 10.15 SDK]'  # friendly name to display in the UI
#     vmImage: 'macOS-10.15'
#     xcodeDeveloperDir: '/Applications/Xcode_11.7.app/Contents/Developer'
#     publishArtifact: false
# - template: .ci/azure/templates/macos-build-pipeline-template.yml
#   parameters:
#     name: macOS_latest
#     displayName: 'macOS [vmImage: macOS-latest]'  # friendly name to display in the UI
#     vmImage: 'macOS-latest'
#     publishArtifact: true
#     artifact: 'warzone2100_macOS (latest)'
