# WZ2100 Azure build pipeline
#
# Currently contains:
#  - macOS builds

trigger:
  branches:
    include:
    - '*'
    - refs/tags/*
    exclude:
    - l10n_*

jobs:
- template: .ci/azure/templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_Xcode_9_4_1
    displayName: 'macOS [Xcode 9.4.1, macOS 10.13 SDK]'  # friendly name to display in the UI
    vmImage: 'macOS-10.14'
    xcodeDeveloperDir: '/Applications/Xcode_9.4.1.app'
    vcpkgBuildXcodeDeveloperDir: '/Applications/Xcode_10.3.app'
    publishArtifact: false
- template: .ci/azure/templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_Xcode_10_3_novideos
    displayName: 'macOS [Xcode 10.3, macOS 10.14 SDK] - no videos'  # friendly name to display in the UI
    vmImage: 'macOS-10.14'
    xcodeDeveloperDir: '/Applications/Xcode_10.3.app' # Set default Xcode to Xcode 10.3 on macOS 10.14
    vcpkgBuildXcodeDeveloperDir: '/Applications/Xcode_10.3.app'
    includeVideos: false
    publishArtifact: true
    artifact: 'warzone2100_macOS_novideos'
    # Upload this macOS job's output to GitHub Releases
    uploadArtifactToGitHubReleases: true
    gitHubConnection: 'githubReleases'
    #
- template: .ci/azure/templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_Xcode_10_3
    displayName: 'macOS [Xcode 10.3, macOS 10.14 SDK] - full'  # friendly name to display in the UI
    vmImage: 'macOS-10.14'
    xcodeDeveloperDir: '/Applications/Xcode_10.3.app' # Set default Xcode to Xcode 10.3 on macOS 10.14
    vcpkgBuildXcodeDeveloperDir: '/Applications/Xcode_10.3.app'
    includeVideos: true
    publishArtifact: true
    artifact: 'warzone2100_macOS'
    # Upload this macOS job's output to GitHub Releases
    uploadArtifactToGitHubReleases: true
    gitHubConnection: 'githubReleases'
    #
- template: .ci/azure/templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_Xcode_11
    displayName: 'macOS [Xcode 11.5, macOS 10.15 SDK]'  # friendly name to display in the UI
    vmImage: 'macOS-10.15'
    xcodeDeveloperDir: '/Applications/Xcode_11.5.app'
    publishArtifact: false
- template: .ci/azure/templates/macos-build-pipeline-template.yml
  parameters:
    name: macOS_latest
    displayName: 'macOS [vmImage: macOS-latest]'  # friendly name to display in the UI
    vmImage: 'macOS-latest'
    publishArtifact: true
    artifact: 'warzone2100_macOS (latest)'
