SUBDIRS=build_tools po win32 3rdparty lib src data pkg

top_srcdir=.
top_builddir=.

include $(top_srcdir)/makerules/common.mk
include $(top_srcdir)/makerules/submake.mk

src: build_tools win32 3rdparty lib
pkg: data src po
