SUBDIRS=build_tools po win32 lib src data packaging

all clean: $(SUBDIRS)

.PHONY: $(SUBDIRS)
$(SUBDIRS):
	$(MAKE) -f Makefile.raw -C $@ $(MAKECMDGOALS)

src: win32 lib build_tools
packaging: data src po
