SRC_FILES=	codeprint.c \
		event.c \
		evntsave.c \
		interp.c \
		script.c \
		script_l.c \
		script_y.c \
		stack.c

LIBS=framework

LIB=script

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

