MAKERULES=../../makerules
include $(MAKERULES)/configure.mk

SRC=block.c \
	configfile.c \
	debug.c \
	frame.c \
	frameresource.c \
	heap.c \
	input.c \
	mem.c \
	mono.c \
	resource_parser.tab.c \
	resource_lexer.lex.c \
	strres.c \
	strres_parser.tab.c \
	strres_lexer.lex.c \
	treap.c \
	trig.c \
	SDL_framerate.c

LIB=framework

include $(MAKERULES)/lib.mk
