include $(top_srcdir)/makerules/common.mk

SRC=configfile.c \
	cursors.c \
	cursors16.c \
	cursors32.c \
	debug.c \
	frame.c \
	frameresource.c \
	input.c \
	i18n.c \
	lexer_input.c \
	printf_ext.c \
	resource_parser.tab.c \
	resource_lexer.lex.c \
	strnlen1.c \
	strres.c \
	strres_parser.tab.c \
	strres_lexer.lex.c \
	tagfile.c \
	treap.c \
	trig.c \
	SDL_framerate.c

LIB=framework

CLEANFILES=strres_parser.tab.h resource_parser.tab.h

include $(top_srcdir)/makerules/lib.mk
