SRC_FILES=	block.c \
		configfile.c \
		debug.c \
		frame_stub.c \
		frameresource.c \
		heap.c \
		input_stub.c \
		mem.c \
		mono.c \
		multiwdg.c \
		resource_l.c \
		resource_y.c \
		strres.c \
		strres_l.c \
		strres_y.c \
		treap.c \
		trig.c \
		wdg.c

LIB=framework

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

