MAKERULES=../../makerules
include $(MAKERULES)/configure.mk

SRC=configfile.c \
	cursors.c \
	cursors16.c \
	cursors32.c \
	debug.c \
	exceptionhandler.c \
	frame.c \
	frameresource.c \
	input.c \
	i18n.c \
	printf_ext.c \
	resource_parser.tab.c \
	resource_lexer.lex.c \
	strnlen1.c \
	strres.c \
	strres_parser.tab.c \
	strres_lexer.lex.c \
	tagfile.c \
	treap.c \
	trig.c \
	SDL_framerate.c

LIB=framework

include $(MAKERULES)/lib.mk
