SRC_FILES=	3dfxdyn.c \
		3dfxfunc.c \
		3dfxmode.c \
		3dfxtext.c \
		bitimage.c \
		bspimd.c \
		bug.c \
		fbf.c \
		imd.c \
		imdload.c \
		ivi.c \
		pcx.c \
		pieblitfunc.c \
		pieclip.c \
		piedraw.c \
		piefunc.c \
		piematrix.c \
		piemode.c \
		piepalette.c \
		piestate.c \
		pietexture.c \
		rendfunc.c \
		rendmode.c \
		stubs.c \
		tex.c \
		textdraw.c \
		v4101_stub.c \
		vsr.c

LIBS=framework

LIB=ivis02

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

