SRC_FILES= \
		bspimd.c \
		ivi.c \
		pcx.c \
		pieblitfunc.c \
		pieclip.c \
		piedraw.c \
		piefunc.c \
		piematrix.c \
		piemode.c \
		piepalette.c \
		piestate.c \
		pietexture.c \
		rendfunc.c \
		rendmode.c \
		screen.c \
		tex.c \
		textdraw.c \
		v4101_stub.c \
		vsr.c

LIBS=framework gamelib ivis_common

LIB=ivis02

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

