MAKERULES=../../makerules
include $(MAKERULES)/configure.mk

SRC=bspimd.c \
	ivi.c \
	pieblitfunc.c \
	pieclip.c \
	piedraw.c \
	piefunc.c \
	piematrix.c \
	piemode.c \
	piepalette.c \
	piestate.c \
	pietexture.c \
	rendfunc.c \
	rendmode.c \
	screen.c \
	tex.c \
	textdraw.c \
	v4101_stub.c \
	vsr.c

LIB=ivis02

include $(MAKERULES)/lib.mk
