MAKERULES=../../../makerules
include $(MAKERULES)/configure.mk

AIVOLUTIONLIST = multiplay commands.txt installation.txt
GRIMLIST = components structs texpages wrf COPYING

AIVOLUTIONARCHIVE=aivolution.wz
GRIMARCHIVE=grim.wz

all:
ifdef DATA
all: $(AIVOLUTIONARCHIVE) $(GRIMARCHIVE)
endif

$(AIVOLUTIONARCHIVE): $(AIVOLUTIONLIST:%=aivolution/%)
	cd aivolution && zip -ru0 ../$@ $(AIVOLUTIONLIST) -x *svn*
	zip -T $@

$(GRIMARCHIVE): $(GRIMLIST:%=grim/%)
	cd grim && zip -ru0 ../$@ $(GRIMLIST) -x *svn*
	zip -T $@

clean:
	$(RMF) $(GRIMARCHIVE)
	$(RMF) $(AIVOLUTIONARCHIVE)

.PHONY: all clean $(AIVOLUTIONARCHIVE) $(GRIMARCHIVE)
