#    Warzone 2100 Lobbyserver, serves as a meeting place to set up games
#    Copyright (C) 2007  Giel van Schijndel
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
include $(abs_top_srcdir)/makerules/configure.mk

OBJS=main.o lobby/read_write_mutex.o networking/tcp_server.o lobby/lobby.o lobby/game.o lobby/raii_counter.o lobby/lobby_iterator.o lobby/lobby_gamelock.o requesthandler.o networking/nattester.o

BOOST_DIR=C:/boost_1_33_1
BOOST_ASIO_DIR=C:/boost_asio_0_3_7
WARZONE_LIBDIR=$(abs_top_builddir)/lib

ifeq ($(RELEASE),)
BOOST_THREADS=$(BOOST_DIR)/bin/boost/libs/thread/build/libboost_thread.lib/mingw/debug/threading-multi/libboost_thread-mgw-mt-d-1_33_1.lib
else
BOOST_THREADS=$(BOOST_DIR)/bin/boost/libs/thread/build/libboost_thread.lib/mingw/release/threading-multi/libboost_thread-mgw-mt-1_33_1.lib
endif

LIBS=-lwsock32 -lws2_32 $(BOOST_THREADS) -lstdc++

LIBDIR=
INCLUDEDIR=-I$(DEVDIR)/include -I$(BOOST_DIR) -I$(BOOST_ASIO_DIR) -I$(WARZONE_LIBDIR)

all: WzMasterServer$(EXEEXT)

WzMasterServer$(EXEEXT): $(OBJS)
	gcc -g $(LIBDIR) -o $@ $^ $(LIBS)

.cpp.o:
	gcc -g -c $(INCLUDEDIR) -Wall -D_WIN32_WINNT=0x0501 -o $@ $<
