FROM ubuntu

RUN apt-get -u update && apt-get -y install build-essential automake libpng12-dev libsdl2-dev libopenal-dev libphysfs-dev libvorbis-dev libtheora-dev libglc-dev libglew1.5-dev libxrandr-dev zip unzip libqt5opengl5-dev libssl-dev qtscript5-dev qt5-default libharfbuzz-dev git cmake gettext ninja-build libnvtt-bin asciidoc
WORKDIR /code
CMD ["sh"]

