top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

SRC= \
	bitimage.cpp \
	imd.cpp \
	imdload.cpp \
	jpeg_encoder.cpp \
	pieclip.cpp \
	piestate.cpp \
	png_util.cpp

LIB=ivis_common

include $(top_srcdir)/makerules/lib.mk
