top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

SRC= \
	bitimage.c \
	imd.c \
	imdload.c \
	pieclip.c \
	piestate.c \
	png_util.c

LIB=ivis_common

include $(top_srcdir)/makerules/lib.mk
