SRC_FILES= \
		bitimage.c \
		bug.c \
		fbf.c \
		imd.c \
		imdload.c \
		pcx.c \
		pieclip.c \
		piestate.c

LIBS=framework gamelib

LIB=ivis_common

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

