name: 'Clean Runner Disk Space (Ubuntu)'
description: 'Cleans disk space in the GitHub Actions Ubuntu Runner image'
runs:
  using: 'composite'
  steps:
    - name: Run cleanup.sh
      shell: bash
      run: |
        echo "Disk space before cleanup:"
        df -h

        # Remove Android SDK directories
        echo "Removing Android SDK directories"
        sudo rm -rf /usr/local/lib/android || true
        sudo rm -rf /opt/android || true
        sudo rm -rf /usr/local/android-sdk || true
        echo "Removing Android SDK directories - complete"
        df -h

        # Remove .NET directories
        echo "Removing .NET directories"
        sudo rm -rf /usr/share/dotnet || true
        echo "Removing .NET directories - complete"
        df -h

        # Remove Haskell directories
        echo "Removing Haskell directories"
        sudo rm -rf /opt/ghc || true
        sudo rm -rf /usr/local/.ghcup || true
        sudo rm -rf /opt/cabal || true
        echo "Removing Haskell directories - complete"
        df -h

        # apt clean
        echo "Running apt-get clean"
        sudo apt-get clean
        echo "Disk space after cleanup:"
        df -h
