top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

SRC= \
	dumpinfo.cpp \
	exceptionhandler.c \
	exchndl.c

LIB=exceptionhandler

include $(top_srcdir)/makerules/lib.mk
