top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

SRC= \
	dumpinfo.cpp \
	exceptionhandler.cpp \
	exchndl.cpp

LIB=exceptionhandler

include $(top_srcdir)/makerules/lib.mk
