top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

# Due to the lexer's dependencies on the parser's header we need to compile the
# parsers first
PARSERS= \
	chat_parser.tab.c \
	chat_lexer.lex.c \
	script_parser.tab.c \
	script_lexer.lex.c

SRC= \
	$(PARSERS) \
	codeprint.c \
	event.c \
	eventsave.c \
	interpreter.c \
	script.c \
	stack.c

LIB=script

CLEANFILES=chat_parser.tab.h script_parser.tab.h $(PARSERS)

include $(top_srcdir)/makerules/lib.mk
