include $(abs_top_srcdir)/makerules/configure.mk

SRC=codeprint.c \
	event.c \
	evntsave.c \
	interp.c \
	script.c \
	chat_parser.tab.c \
	chat_lexer.lex.c \
	script_parser.tab.c \
	script_lexer.lex.c \
	stack.c

LIB=script

CLEANFILES=chat_parser.tab.h script_parser.tab.h

include $(abs_top_srcdir)/makerules/lib.mk

