-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "cam1-5.slo"

-- generic value file for cam1-5.gam

-- General Values
player = 0
-- barbarians
enemy1 = 7
-- New Paradigm (base2)
enemy2 = 1
-- scavenger start power
pow1 = 500
-- NP start power
pow2 = 2000

-- Set Structure Limits
powerGen = "A0PowerGenerator"
oilDerrick = "A0ResourceExtractor"
research = "A0ResearchFacility"
factory = "A0LightFactory"
command = "A0CommandCentre"
comRelay = "A0ComDroidControl"
-- Limit on number of Power Generator Buildings
numPow = 0
-- Limit on number of resource Extractors
numExt = 0
-- Limit on number of Factory Buildings
numFac = 0
-- Limit on number of Research Facility Buildings
numRes = 0

-- Base Under Attack
attackSnd1 = "pcv337.ogg"

-- Win or lose
-- mision failed
lostSnd = "pcv470.ogg"
NextLev = "CAM_1A-C"

-- Briefing Stuff
MissionBrief = "SB1_5_MSG"
endMsg = "END"
-- winMsg		INTMESSAGE	"WIN"

-- Return to LZ Message

LZ_MSG = "C1-5_LZ"
obj1 = "C1-5_OBJ1"
LZSnd = "pcv427.ogg"
ReinforceSnd = "pcv440.ogg"
-- number of seconds*10 for transport, -1 for no reinforcements
ReinforceTime = 1800
LZComp = "pcv445.ogg"
LZClear = "lz-clear.ogg"

-- Transport exit and entry
entryX = 1
entryY = 55
exitX = 15
exitY = 62

-- for enemy transports
transporter = "Transporter"
warnSnd = "pcv395.ogg"

-- Proximity: Artifacts
crate = "Crate"

-- Player Bonus Research Topics given on completion of mission
-- number of topics to enable
numResP0 = 0
-- resP0[0]	RESEARCHSTAT	"CAM1RESEARCH" //"R-Struc-Factory-Upgrade03"
-- resP0[1]	RESEARCHSTAT	"CAM1RESEARCH" //"R-Struc-RprFac-Upgrade01"
-- resP0[2]	RESEARCHSTAT	"CAM1RESEARCH" //"R-Sys-Resistance-Upgrade01"
-- resP0[3]	RESEARCHSTAT	"CAM1RESEARCH" //"R-Sys-SpyTurret"
-- resP0[4]	RESEARCHSTAT	"CAM1RESEARCH" //"R-Vehicle-Body11"
-- resP0[5]	RESEARCHSTAT	"CAM1RESEARCH" //"R-Vehicle-Engine03"

art1X = 4288
art1Y = 4160
-- get this from NP Cyborg Factory
art1Get = getStructureByID(407)
art1Snd2 = "pcv352.ogg"
-- art1Msg		INTMESSAGE	"C1-5_ART1"
art1Comp = "R-Struc-Factory-Upgrade03"

art2X = 5696
art2Y = 2368
-- Right factory
art2Get = getStructureByID(483)
art2Snd2 = "pcv352.ogg"
-- art2Msg		INTMESSAGE	"C1-5_ART2"
art2Comp = "R-Vehicle-Engine02"


art6X = 5184
art6Y = 2624
-- factory
art6Get = getStructureByID(481)
art6Snd2 = "pcv352.ogg"
-- art6Msg		INTMESSAGE	"C1-5_ART6"
art6Comp = "R-Vehicle-Body08"

art7X = 5568
art7Y = 3136
-- research Fac	MUST BE SYNAPTIC LINK for briefing to hold true
art7Get = getStructureByID(485)
art7Snd2 = "pcv352.ogg"
-- art7Msg		INTMESSAGE	"C1-5_ART7"
art7Comp = "R-Comp-SynapticLink"


-- Proximity: Enemy

-- scavenger
-- base1
-- Northern Scavenger light factory
enm1a = getStructureByID(223)
enm1aID = 223
-- SW Scavenger light factory
enm1b = getStructureByID(280)
enm1bID = 280
-- SE Scavenger light factory
enm1c = getStructureByID(279)
enm1cID = 279

-- 388	//guntower
enm1See = getStructureByID(207)
enm1Msg = "C1-5_BASE1"
enm1Snd1 = "pcv374.ogg"
enm1Snd2 = "pcv392.ogg"

enm2See = getStructureByID(109)
enm2Msg = "C1-5_BASE2"
enm2Snd1 = "pcv374.ogg"
enm2Snd2 = "pcv392.ogg"

-- 95
enm3See = getStructureByID(85)
enm3Msg = "C1-5_BASE3"
enm3Snd1 = "pcv374.ogg"
enm3Snd2 = "pcv392.ogg"

-- base eradicated
enm4Snd2 = "pcv394.ogg"

-- New Paradigm
-- base2
-- Left Heavy factory New Paradigm
enm2a = getStructureByID(481)
enm2aID = 481
-- Right Heavy factory New Paradigm
enm2b = getStructureByID(483)
enm2bID = 483
-- Cyborg factory New Paradigm
enm2c = getStructureByID(407)
enm2cID = 407

-- AI STUFF

-- position of player LZ
playerX = 836
playerY = 7232

-- General Values
-- build total-ish
enemy1Tot = 6
-- build total-ish
enemy2Tot = 6

-- Enemy Tactics
-- scavenger Templates
template1 = {}
template1[0] = "BaBaPeople"
template1[1] = "BarbarianTrike"
template1[2] = "BarbarianBuggy"
template1[3] = "BabaJeep"
template1[4] = "BarbarianRKBuggy"
template1[5] = "BabaRKJeep"
template1[6] = "BabaBusCan"
template1[7] = "BabaFireCan"

-- NP Vehicle Templates
template2 = {}
template2[0] = "NP-L-RocketPod-Wheels"
template2[1] = "NP-L-Sensor-Wheels"
template2[2] = "NP-M-MdCannon-Tracks"
template2[3] = "NP-M-LtMortar-Halftrack"
template2[4] = "NP-M-MdCannon-Halftrack"
template2[5] = "NP-H-MdCannon-Tracks"
template2[6] = "NP-L-MRLS-Halftrack"
template2[7] = "NP-L-HMG-Halftrack"
template2[8] = "NP-M-BB-Halftrack"
-- "ConstructionDroidNP"
template2[9] = "NP-M-CON-Track"

-- NP Cyborg Templates
template3 = {}
template3[0] = "Cyb-Chain-GROUND"
template3[1] = "Cyb-Flamer-GROUND"

-- Reinforce Lists for New Paradigm Transports
numScout = 3
scout = {}
scout[0] = "NP-L-Sensor-Wheels"
scout[1] = "NP-L-RocketPod-Wheels"
scout[2] = "NP-L-HMG-Halftrack"

numHeavy = 3
heavy = {}
heavy[0] = "NP-M-LitCannon-Halftrack"
heavy[1] = "NP-M-MdCannon-Tracks"
heavy[2] = "NP-M-LtMortar-Halftrack"

-- starting Technology
-- Enemy1 Scavs
numtecE1 = 2
tecE1 = {}
tecE1[0] = "R-Wpn-MG-Damage03"
tecE1[1] = "R-Wpn-Rocket-Damage02"

-- Enemy2 NP
numtecE2 = 20
tecE2 = {}
tecE2[0] = "R-Defense-WallUpgrade02"
tecE2[1] = "R-Struc-Materials02"
tecE2[2] = "R-Struc-Factory-Upgrade02"
tecE2[3] = "R-Struc-Factory-Cyborg-Upgrade02"
tecE2[4] = "R-Vehicle-Engine02"
tecE2[5] = "R-Vehicle-Metals02"
tecE2[6] = "R-Cyborg-Metals02"
tecE2[7] = "R-Wpn-Cannon-Accuracy01"
tecE2[8] = "R-Wpn-Cannon-Damage03"
tecE2[9] = "R-Wpn-Flamer-Damage03"
tecE2[10] = "R-Wpn-Flamer-ROF01"
tecE2[11] = "R-Wpn-MG-Damage04"
tecE2[12] = "R-Wpn-MG-ROF01"
tecE2[13] = "R-Wpn-Mortar-Acc01"
tecE2[14] = "R-Wpn-Mortar-Damage03"
tecE2[15] = "R-Wpn-Rocket-Accuracy01"
tecE2[16] = "R-Wpn-Rocket-Damage03"
tecE2[17] = "R-Wpn-Rocket-ROF02"
tecE2[18] = "R-Wpn-RocketSlow-Damage02"
tecE2[19] = "R-Struc-RprFac-Upgrade03"

--run the code
dofile('cam1-5_logic.lua')
