-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "cam1A-C.slo"

-- script file for tutorial, cam1A-C.gam

-- General Values
player = 0
-- New Paradigm
enemy1 = 1
-- New Paradigm
enemy2 = 1
-- NP start power
pow1 = 500
-- NP start power
pow2 = 500

-- Briefing Stuff
MissionBrief = "MB1A-C_MSG"
MissionBrief2 = "MB1A-C_MSG2"
endMsg = "END"
-- winMsg		INTMESSAGE	"WIN"

-- Base Under Attack
attackSnd1 = "pcv337.ogg"

-- Win or lose
-- mision failed
lostSnd = "pcv470.ogg"
NextLev = "SUB_1_7S"
-- (1 hour) number of seconds*10 for mission, -1 for unlimited
timeLimit = 36000

-- for enemy transports
transporter = "Transporter"

-- obj1		INTMESSAGE	"C1A-C_OBJ1"

-- Player Bonus Research Topics given on completion of mission
-- number of topics to enable
numResP0 = 0
resP0 = {}
resP0[0] = "R-Wpn-MG1Mk1"

-- Reinforce Lists for New Paradigm
numReinf = 3
reinfTemp = {}
reinfTemp[0] = "NP-H-HvyCannon-Tracks"
reinfNum = {}
reinfNum[0] = 10
reinfTemp[1] = "NP-M-Sensor-Wheels"
reinfNum[1] = 1
reinfTemp[2] = "NP-M-HvyMortar-Halftrack"
reinfNum[2] = 6

-- se corner
reinfPosX1 = 15424
reinfPosY1 = 16064
-- ne road
reinfPosX2 = 12736
reinfPosY2 = 128

-- NP Vehicle Templates
template2 = {}
template2[0] = "NP-L-RocketPod-Wheels"
template2[1] = "NP-L-Sensor-Wheels"
template2[2] = "NP-M-MdCannon-Tracks"
template2[3] = "NP-M-LtMortar-Halftrack"
template2[4] = "NP-M-MdCannon-Halftrack"
template2[5] = "NP-H-MdCannon-Tracks"
template2[6] = "NP-L-MRLS-Halftrack"
template2[7] = "NP-L-HMG-Halftrack"
template2[8] = "NP-M-BB-Halftrack"
-- "ConstructionDroidNP"
template2[9] = "NP-M-CON-Track"
template2[10] = "NP-H-HvyCannon-Tracks"
template2[11] = "NP-M-Sensor-Wheels"
template2[12] = "NP-M-HvyMortar-Halftrack"

-- NP Cyborg Templates
template3 = {}
template3[0] = "Cyb-Chain-GROUND"
template3[1] = "Cyb-Cannon-GROUND"
template3[2] = "Cyb-Flamer-GROUND"


-- new enemy LZs
numLZ = 5
-- 15552
enemyLZX = {}
enemyLZX[0] = 15424
-- 14912
enemyLZY = {}
enemyLZY[0] = 15424
enemyLZM = {}
enemyLZM[0] = "C1A-C_LZ1"
enemyLZX[1] = 12736
enemyLZY[1] = 1312
enemyLZM[1] = "C1A-C_LZ2"
-- 7560
enemyLZX[2] = 8768
-- 15040
enemyLZY[2] = 15424
enemyLZM[2] = "C1A-C_LZ3"
-- 7744
enemyLZX[3] = 1344
-- 1856
enemyLZY[3] = 8896
-- need to change
enemyLZM[3] = "C1A-C_LZ4"
enemyLZX[4] = 5056
enemyLZY[4] = 3264
enemyLZM[4] = "C1A-C_LZ5"
warnSnd = "pcv395.ogg"

-- new targets (each grouped in 3, near initial LZ)
-- Goes for Derricks more now!!!
numTargets = 3
-- SE corner
targetX = {}
targetX[0] = 14272
targetY = {}
targetY[0] = 12608
targetX[1] = 12736
targetY[1] = 13504
targetX[2] = 10560
targetY[2] = 15168

-- North Road
targetX[3] = 8896
targetY[3] = 7488
targetX[4] = 11840
targetY[4] = 3392
targetX[5] = 14656
targetY[5] = 832

-- Canyon
targetX[6] = 10304
targetY[6] = 14912
targetX[7] = 3648
targetY[7] = 13760
targetX[8] = 4928
targetY[8] = 10304

-- Hill south of PLayer base
targetX[9] = 1600
targetY[9] = 7744
-- player's LZ
targetX[10] = 1472
targetY[10] = 6720
targetX[11] = 3648
targetY[11] = 13888

-- 1A North road
targetX[12] = 4928
targetY[12] = 2112
targetX[13] = 3776
targetY[13] = 4928
-- Player's LZ
targetX[14] = 1472
targetY[14] = 6720

-- Set Structure Limits
powerGen = "A0PowerGenerator"
oilDerrick = "A0ResourceExtractor"
research = "A0ResearchFacility"
factory = "A0LightFactory"
-- powerModuleHack		STRUCTURESTAT		"PowMod1"
command = "A0CommandCentre"
comRelay = "A0ComDroidControl"
-- Limit on number of Power Generator Buildings
numPow = 5
-- Limit on number of resource Extractors
numExt = 200
-- Limit on number of Factory Buildings
numFac = 5
-- Limit on number of Research Facility Buildings
numRes = 5

-- starting Technology
-- Enemy2 NP
numtecE2 = 20
tecE2 = {}
tecE2[0] = "R-Defense-WallUpgrade02"
tecE2[1] = "R-Struc-Materials02"
tecE2[2] = "R-Struc-Factory-Upgrade02"
tecE2[3] = "R-Struc-Factory-Cyborg-Upgrade02"
tecE2[4] = "R-Vehicle-Engine02"
tecE2[5] = "R-Vehicle-Metals02"
tecE2[6] = "R-Cyborg-Metals02"
tecE2[7] = "R-Wpn-Cannon-Accuracy01"
tecE2[8] = "R-Wpn-Cannon-Damage03"
tecE2[9] = "R-Wpn-Flamer-Damage03"
tecE2[10] = "R-Wpn-Flamer-ROF01"
tecE2[11] = "R-Wpn-MG-Damage04"
tecE2[12] = "R-Wpn-MG-ROF01"
tecE2[13] = "R-Wpn-Mortar-Acc01"
tecE2[14] = "R-Wpn-Mortar-Damage03"
tecE2[15] = "R-Wpn-Rocket-Accuracy01"
tecE2[16] = "R-Wpn-Rocket-Damage03"
tecE2[17] = "R-Wpn-Rocket-ROF02"
tecE2[18] = "R-Wpn-RocketSlow-Accuracy01"
tecE2[19] = "R-Wpn-RocketSlow-Damage02"

--run the code
dofile('cam1a-c_logic.lua')
