-- Generated by wz2lua (implementation file)
version(0) --- version of the script API this script is written for

-- video and text to play during this mission

-- Structure Limits

-- Initialisation

-- Briefings

-- Time Limit

-- 'Globals'
-- mission lost

-- General variables
-- for while loops
count = 0
count2 = 0
countBriefs = 0
temp = 0
temp1 = 0
temp2 = 0
tempX = 0
tempY = 0
videoOver = false


-- ********************
-- Events
-- ********************

-- Declared Events

-- Initialisation
function start()
	centreViewPos(centreX, centreY)
	
	-- set scroll limits
	-- setScrollParams(scrollX1, scrollY1, scrollX2, scrollY2);
	
	-- set radar zoom level
	setRadarZoom(zoomLevel)
	
	-- set Mission time limit
	setMissionTime(timeLimit/10.0)
	-- make sure reinforcements disabled
	setReinforcementTime(-1/10.0)
	-- set LZ and no go areas - shouldn't need to do this any more - it is until all NoGoAreas are saved in the save game info
	-- The LZ can now be set up just before FlyTransporterIn()
	initAllNoGoAreas()
	count = 0
	while count < numLZ do
		setNoGoArea(LZX[count] - 1, LZY[count] - 1, LZX[count] + 1, LZY[count] + 1, count)
		count = count + 1
	end
	
	-- set structure limits
	count = 0
	while count < numStrucStats do
		setStructureLimits(strucStat[count], strucLimit[count], player)
		enableStructure(strucStat[count], player)
		count = count + 1
	end
	
	-- place transport
	addDroid(transporter, (LZX[0] * 128) + 64, (LZY[0] * 128) + 64, player)
	setTransporterExit(player, exitX, exitY)
	
	videoOver = false
	
	-- play mission brief(s)
	if numBriefs > 0 then
		if briefVal[0] < 2 then
			addMessage(brief[0], MISS_MSG, 0, true)
		else
			addMessage(brief[0], MISS_MSG, 0, false)
			-- last briefing?
			if countBriefs >= numBriefs then
				deactivateEvent(briefings)
			end
		end
		countBriefs = 1
	end
end
callbackEvent(start, CALL_GAMEINIT)

-- need to rework this better!!
function briefings()
	if briefVal[countBriefs - 1] == 0 then
		removeMessage(brief[countBriefs - 1], MISS_MSG, 0)
	end
	
	-- last briefing? (this is not played immediate!)
	if countBriefs == numBriefs - 1 then
		playVideo(cam1EndVideo, cam1EndText)
		videoOver = true
	end
	
	-- video over with?
	if videoOver then
		deactivateEvent(briefings)
	end
	
	-- add next brief
	if countBriefs < numBriefs then
		if briefVal[countBriefs] < 2 then
			addMessage(brief[countBriefs], MISS_MSG, 0, true)
		else
			addMessage(brief[countBriefs], MISS_MSG, 0, false)
		end
		countBriefs = countBriefs + 1
	end
end
callbackEvent(briefings, CALL_VIDEO_QUIT)

function nextLevEvnt()
	startMission(OFF_KEEP, NextLev)
	deactivateEvent(nextLevEvnt)
	setCampaignNumber(2)
end
callbackEvent(nextLevEvnt, CALL_START_NEXT_LEVEL)

function gameLost()
	gameOverMessage(endMsg, MISS_MSG, 0, false)
	deactivateEvent(gameLost)
end

-- out of time?
function timeUp()
	playSound(lostSnd, 0)
	-- waits 2 seconds before ending
	repeatingEvent(gameLost, 2.0)
	deactivateEvent(timeUp)
end
callbackEvent(timeUp, CALL_MISSION_TIME)


---------- stubs ----------

if startMission == nil then startMission = function() print("stub: startMission"); return 0 end end
if setEventTrigger == nil then setEventTrigger = function() print("stub: setEventTrigger"); return 0 end end
if addMessage == nil then addMessage = function() print("stub: addMessage"); return 0 end end
if addDroid == nil then addDroid = function() print("stub: addDroid"); return 0 end end
if setRadarZoom == nil then setRadarZoom = function() print("stub: setRadarZoom"); return 0 end end
if playVideo == nil then playVideo = function() print("stub: playVideo"); return 0 end end
if gameOverMessage == nil then gameOverMessage = function() print("stub: gameOverMessage"); return 0 end end
if enableStructure == nil then enableStructure = function() print("stub: enableStructure"); return 0 end end
if removeMessage == nil then removeMessage = function() print("stub: removeMessage"); return 0 end end
if setMissionTime == nil then setMissionTime = function() print("stub: setMissionTime"); return 0 end end
if setReinforcementTime == nil then setReinforcementTime = function() print("stub: setReinforcementTime"); return 0 end end
if setStructureLimits == nil then setStructureLimits = function() print("stub: setStructureLimits"); return 0 end end
if setNoGoArea == nil then setNoGoArea = function() print("stub: setNoGoArea"); return 0 end end
if setTransporterExit == nil then setTransporterExit = function() print("stub: setTransporterExit"); return 0 end end
if centreViewPos == nil then centreViewPos = function() print("stub: centreViewPos"); return 0 end end
if playSound == nil then playSound = function() print("stub: playSound"); return 0 end end
if setCampaignNumber == nil then setCampaignNumber = function() print("stub: setCampaignNumber"); return 0 end end
if initAllNoGoAreas == nil then initAllNoGoAreas = function() print("stub: initAllNoGoAreas"); return 0 end end
