-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "cam2endX.slo"

-- cam2endX.vlo
-- just gets the slo file to load

-- Next level stuff
-- Start of campaign 3 (define in cam2endX.vlo?)
NextLev = "CAM_3A"

-- Structure Limits
-- MAX 5. Must be same as number of limits given next
numStrucStats = 6
strucStat = {}
strucStat[0] = "A0PowerGenerator"
strucLimit = {}
strucLimit[0] = 5
strucStat[1] = "A0ResourceExtractor"
strucLimit[1] = 200
strucStat[2] = "A0ResearchFacility"
strucLimit[2] = 5
strucStat[3] = "A0LightFactory"
strucLimit[3] = 5
strucStat[4] = "A0CommandCentre"
strucLimit[4] = 1
strucStat[5] = "A0ComDroidControl"
strucLimit[5] = 1

-- Initialisation
-- starting view centre (in world units)
centreX = 11200
centreY = 12864
-- scroll limits (in tile units)
scrollX1 = 0
scrollY1 = 0
scrollX2 = 128
scrollY2 = 128
-- starting radar: 0=zoomed out, 2=zoomed in
zoomLevel = 0

-- MAX 8. Number of Landing zones/areas can't build on (0 = LZ)
numLZ = 3
-- coords of Alpha's LZs in tile units
LZX = {}
LZX[0] = 87
LZY = {}
LZY[0] = 100
-- 97	//coords of Beta's LZ in tile units
LZX[1] = 87
-- 97	//no longer req'd
LZY[1] = 100
-- coords of Collective's LZ in tile units
LZX[2] = 117
LZY[2] = 116

-- Transport exit coords
-- 126	//same as 2-8 since safe haven
transX = {}
transX[1] = 1
-- 60
transY = {}
transY[1] = 55

-- 7mins (+1 min for transport move)	5400	// (9 minute) number of seconds*10 for transport, -1 for no reinforcements
ReinforceTime = 4200

-- Briefings
-- MAX 5. Needs to be same as the number of briefings given next
numBriefs = 2
brief = {}
brief[0] = "MB2_DII_MSG"
brief[1] = "MB2_DII_MSG2"
-- played at end, so not part of normal briefs
brief[2] = "CAM2_OUT"
-- 0 remove after playing, 1 keep, 2 don't play immediately
briefVal = {}
briefVal[0] = 0
-- 0 remove after playing, 1 keep, 2 don't play immediately
briefVal[1] = 1
-- briefVal[2]	int		2	//0 remove after playing, 1 keep, 2 don't play immediately
endMsg = "END"

-- Time Limit for this and Sub map
-- 30mins //45 mins (set -1 for no time limit, otherwise time in 1/10s)
timeLimit = 18000

-- 'Globals'
-- These should be same in each file, but may need slight alterations
-- player's player number
player = 0
-- mission failed
lostSnd = "pcv470.ogg"
transporter = "Transporter"

-- Enemy Starting Technology
-- The Collective
enemy = {}
enemy[0] = 2
numTechs = 33
startTech = {}
startTech[0] = "R-Defense-WallUpgrade06"
startTech[1] = "R-Struc-Materials06"
startTech[2] = "R-Struc-Factory-Upgrade06"
startTech[3] = "R-Struc-Factory-Cyborg-Upgrade06"
startTech[4] = "R-Struc-VTOLFactory-Upgrade03"
startTech[5] = "R-Struc-VTOLPad-Upgrade03"
startTech[6] = "R-Vehicle-Engine06"
startTech[7] = "R-Vehicle-Metals06"
startTech[8] = "R-Cyborg-Metals06"
startTech[9] = "R-Sys-Engineering02"
startTech[10] = "R-Wpn-AAGun-Accuracy01"
startTech[11] = "R-Wpn-AAGun-Damage01"
startTech[12] = "R-Wpn-AAGun-ROF01"
startTech[13] = "R-Wpn-Bomb-Accuracy01"
startTech[14] = "R-Wpn-Cannon-Accuracy02"
startTech[15] = "R-Wpn-Cannon-Damage06"
startTech[16] = "R-Wpn-Cannon-ROF03"
startTech[17] = "R-Wpn-Flamer-Damage06"
startTech[18] = "R-Wpn-Flamer-ROF03"
startTech[19] = "R-Wpn-Howitzer-Accuracy02"
startTech[20] = "R-Wpn-Howitzer-Damage03"
startTech[21] = "R-Sys-Sensor-Upgrade01"
startTech[22] = "R-Wpn-MG-Damage07"
startTech[23] = "R-Wpn-MG-ROF03"
startTech[24] = "R-Wpn-Mortar-Acc02"
startTech[25] = "R-Wpn-Mortar-Damage06"
startTech[26] = "R-Wpn-Mortar-ROF03"
startTech[27] = "R-Wpn-Rocket-Accuracy02"
startTech[28] = "R-Wpn-Rocket-Damage06"
startTech[29] = "R-Wpn-Rocket-ROF03"
startTech[30] = "R-Wpn-RocketSlow-Accuracy03"
startTech[31] = "R-Wpn-RocketSlow-Damage06"
startTech[32] = "R-Wpn-RocketSlow-ROF03"

-- VTOL ATTACK
padPlayer = 2

numVTOL = 2

-- number of droids in group
VTOLsize = {}
VTOLsize[0] = 5
templatesVTOL = {}
templatesVTOL[0] = {}
templatesVTOL[0][0] = "CO-M-Bomb2-VTOL"
templatesVTOL[0][1] = "CO-L-Bomb1-VTOL"
-- 0 - droid, 1 - structure
targetObjType = {}
targetObjType[0] = 1
-- start	(*10secs)
startTime = {}
startTime[0] = 1
-- 30sec	(*10secs)
everyTime = {}
everyTime[0] = 3

-- number of droids in group
VTOLsize[1] = 5
-- "CO-M-HVAT-V"
templatesVTOL[1] = {}
templatesVTOL[1][0] = "CO-L-RotMG-VTOL"
-- "CO-L-Rocket-LtA-T-VTOL"
templatesVTOL[1][1] = "CO-M-HVAT-V"
-- 0 - droid, 1 - structure
targetObjType[1] = 0
-- start	(*10secs)
startTime[1] = 0
-- 30sec	(*10secs)
everyTime[1] = 3

-- 30
vanishX = 127
-- 0
vanishY = 64

-- attack area for targets
-- target anything in 2A
baseX1 = 8192
baseY1 = 8192
baseX2 = 16384
baseY2 = 16384

-- positions to come onto map (randomised)
-- North road
groupX = {}
groupX[0] = 12696
groupY = {}
groupY[0] = 64
-- NE Hill
groupX[1] = 16192
groupY[1] = 8256
-- between 0 and 1 (NE)
groupX[2] = 16192
groupY[2] = 3520
-- NW Top
groupX[3] = 4544
groupY[3] = 64
-- NW Left
groupX[4] = 64
groupY[4] = 3520


-- Ground Forces
-- The Collectives entry/exit for Transport
-- define transport entry exit for each enemy!
entryX = {}
entryX[0] = 126
-- unnecessary if no enemy transports (defaults 0)
entryY = {}
entryY[0] = 100
-- leave as 0 if don't want a transport adding for this enemy
exitX = {}
exitX[0] = 126
exitY = {}
exitY[0] = 70

-- Transport Scouts
templates = {}
templates[0] = "Cyb-Chain-GROUND"
templates[1] = "CO-M-HMG-T"
templates[2] = "Cyb-Cannon-GROUND"
-- North Tanks
templates[3] = "CO-M-Rocket-HvyA-T-Track"
templates[4] = "CO-H-RotCan-Track"
templates[5] = "CO-H-HPVCannon-Tracks"
templates[6] = "CO-M-ROTMG-T"
templates[7] = "CO-H-QuadBofAA-T"
-- South Cyborgs
templates[8] = "Cyb-Rocket-GROUND"
templates[9] = "Cyb-RotMG-GROUND"
templates[10] = "Cyb-Cannon-GROUND"
templates[11] = "CO-M-Rocket-HvyA-T-Track"
templates[12] = "CO-H-HPVCannon-Tracks"
templates[13] = "Cyb-Rocket-GROUND"
templates[14] = "Cyb-Cannon-GROUND"


-- ********************************************
-- coordinates (world coords)		MAX = 10
-- ********************************************
-- phantom factory 0 assembly (N edge of map) TANKS
coordsX = {}
coordsX[0] = 12096
coordsY = {}
coordsY[0] = 320
-- 8256		//phantom factory 1 assembly (S edge of map) Cyborgs
coordsX[1] = 15680
-- 16192
coordsY[1] = 15936
-- phantom factory 2 assembly (W edge of map) TANKS
coordsX[2] = 320
coordsY[2] = 14272

-- way 1 (Northern Oil 2B)
coordsX[3] = 10048
coordsY[3] = 1984
-- way 2 (mid base Oil 2B)
coordsX[4] = 12096
coordsY[4] = 6592
-- way 3 (NE oil 2A)
coordsX[5] = 14528
coordsY[5] = 9664
-- way 4 (Player's LZ)
coordsX[6] = 10944
coordsY[6] = 13248
-- way 5 (Player's LZ#2)
coordsX[7] = 12608
coordsY[7] = 12480
--[[reuse
coordsX		[8]	int		1728		//hillgroup waypoint4
coordsY		[8]	int		7744]]--

-- ********************************************
-- Enemy Groups
-- ********************************************
-- group MAX = 10
numGroups = 2
-- ambush version
-- GROUP on North edge of map
-- 0 = Ambush/Patrol, 1 = Defence, 2 = Scout, 3 = Attack...
grpType = {}
grpType[0] = 0
-- player number (collective)
grpPlayer = {}
grpPlayer[0] = 0
-- starting group (gets reinforced with edge stuff)
grpRegion = {}
grpRegion[0] = -1
-- 10s. (always make >= 0 for defence forces)
grpTimeGo = {}
grpTimeGo[0] = 0
-- grpRegionGo		[0]	int		-1		//index in regions array as trigger
-- grpWhoGo		[0]	int		0		//player number to cross trigger region (may not need?)
-- don't set morale/leadership/retreat
grpMorale = {}
grpMorale[0] = -1
-- grpLeadership	[0]	int		0		//leadership value
-- grpRetreatXY	[0]	int		0		//retreat to base 1 assembly
-- 3		//index in coords/sectors array (depends on grpType)
grpPosStart = {}
grpPosStart[0] = 2
-- 3		//Minimum index in coords array
grpPosMin = {}
grpPosMin[0] = 2
-- Maximum index in coords array
grpPosMax = {}
grpPosMax[0] = 7
-- Step increase for next 'waypoint'
grpPosStep = {}
grpPosStep[0] = 1
-- 0 = stop, 1 = loop, 2 = pingpong, 3 = random thru waypoints
grpPosType = {}
grpPosType[0] = 0
-- index factory to reinforce group. -1 = any factory.
grpFactory = {}
grpFactory[0] = 0
-- ideal size. If less than this factory will reinforce
grpIdealSize = {}
grpIdealSize[0] = 99

-- GROUP from South of map (Cyborgs)
-- 0 = Ambush/Patrol, 1 = Defence, 2 = Scout, 3 = Attack...
grpType[1] = 0
-- player number (Collective)
grpPlayer[1] = 0
-- region
grpRegion[1] = -1
-- sensor will move this group
grpTimeGo[1] = 0
-- grpRegionGo		[1]	int		-1		//no region. index in regions array as trigger
-- grpWhoGo		[1]	int		0		//player number to cross trigger region (may not need?)
-- morale = 50%
grpMorale[1] = -1
-- grpLeadership	[1]	int		0		//leadership value
-- grpRetreatXY	[1]	int		0		//retreat (index in coords array) base1 assembly
-- don't use
grpPosStart[1] = 7
--
grpPosMin[1] = 5
--
grpPosMax[1] = 7
--
grpPosStep[1] = -1
--
grpPosType[1] = 1
-- index structure to reinforce group. -1 = any factory.
grpFactory[1] = 1
-- ideal size. If less than this factory will reinforce
grpIdealSize[1] = 99


-- Factories
-- MAX = 10
numFactories = 2
-- Tank Factory
-- plonked on map (phantom factories)
factID = {}
factID[0] = -1
-- index to assembly point. -1 for don't set
factAssXY = {}
factAssXY[0] = 0
-- 10sec
factTimeGo = {}
factTimeGo[0] = 1
-- factRegionGo		[0]	int		-1		//-1 = no region for trigger (assume WhoGo = 0)
-- index to starting template
factTempMin = {}
factTempMin[0] = 3
-- index to maximum template
factTempMax = {}
factTempMax[0] = 7
-- 4min	//42		//7 min .Time in 10s for factory to try to produce again
factEvery = {}
factEvery[0] = 24

-- cyborg factory
-- transport factory (phantom factories)
factID[1] = -1
-- index to LZ
factAssXY[1] = 1
-- 10sec	//24		//4mins before start
factTimeGo[1] = 1
-- factRegionGo		[1]	int		-1		//-1 = no region for trigger (assume WhoGo = 0)
-- cyborgs
factTempMin[1] = 8
--
factTempMax[1] = 14
-- 5min	////60		//10 mins .Time in 10s for factory to try to produce again
factEvery[1] = 30


-- 'Globals'
-- These should be same in each file, but may need slight alterations
-- enemy transport landing
transSnd = "pcv381.ogg"

--run the code
dofile('cam2endx_logic.lua')
