-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "cam2ax.slo"

-- VLO file for pre-damaging objects

-- cam2AX.VLO

-- 2000	//player's starting power for this campaign
startPow = 5000
player = 0

-- MAX = 10
numStructs = 10

-- derrick flamer
structs = {}
structs[0] = getStructureByID(4499)
-- entrance flamer
structs[1] = getStructureByID(4496)
-- entrance cannon tower
structs[2] = getStructureByID(4446)
-- structs	[3]	STRUCTURE	4142	//entrance cannon tower
-- structs	[4]	STRUCTURE	4457	//corner Lancer tower
-- AA emplacement
structs[3] = getStructureByID(4493)
-- entrance wall
structs[4] = getStructureByID(4456)
-- lancer tower
structs[5] = getStructureByID(4458)
-- broken wall cannon tower
structs[6] = getStructureByID(4462)
-- broken wall wall
structs[7] = getStructureByID(1172)
-- command relay
structs[8] = getStructureByID(1347)
-- 1186	//research facility
structs[9] = getStructureByID(4547)

-- MAX = 2
numDroids = 2
--[[droids	[0]	DROID		4141
droids	[1]	DROID		4140]]--
-- python
droids = {}
droids[0] = 4505
-- python
droids[1] = 4506

-- extra briefing for when Player Transport Lands
brief = "MB2A_MSG2"
incomingSnd = "pcv455.ogg"

--run the code
dofile('cam2ax_logic.lua')
