-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "cam3-2X.slo"

-- VLO file for changing colour of player units on map,
-- so can be found later on Cam3-2

-- cam3-2X.VLO

curPlayer = 1
player = 0
enemy = 3
-- need to give Team Alpha power to repair!!
power = 5000
-- whole map for area to change player 1 to player 0
RegionsX1 = {}
RegionsX1[0] = 64
RegionsY1 = {}
RegionsY1[0] = 64
RegionsX2 = {}
RegionsX2[0] = 5568
RegionsY2 = {}
RegionsY2[0] = 11712
-- extra region for triggering brief1
-- 64
RegionsX1[1] = 64
-- 8640
RegionsY1[1] = 4544
-- 5568
RegionsX2[1] = 5568
-- 11712
RegionsY2[1] = 5568

-- Team Alpha units
numDroids = 13
droids = {}
droids[0] = 369
droids[1] = 370
droids[2] = 371
droids[3] = 372
droids[4] = 373
droids[5] = 374
droids[6] = 375
droids[7] = 376
droids[8] = 377
droids[9] = 378
droids[10] = 379
droids[11] = 380
droids[12] = 381

-- warning about VTOL strike
MissionBrief1 = "MB3_2_MSG3"
-- Team Alpha OK, lead to LZ
MissionBrief2 = "MB3_2_MSG4"
incomingSnd = "pcv456.ogg"

-- "Objective destroyed"
badSnd = "pcv622.ogg"
-- (3 minute) number of seconds*10 for transport, -1 for no reinforcements
ReinforceTime = 1800

--run the code
dofile('cam3-2x_logic.lua')
