-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "GenExp.slo"

-- Generic VLO file template for start/expand levels

-- Cam3b.vlo

-- Next level stuff
-- points to next level
NextLev = "SUB_3_2S"
-- cut out sub map 3-2 for now
-- NextLev		LEVEL		"CAM3A-B"	//points to next level

-- Define Players/Enemies
-- MAX 2. Must define same as number of enemy players given next
numEnemies = 2
-- Nexus
enemy = {}
enemy[0] = 3
-- Gamma
enemy[1] = 1
-- ally player with Gamma
alliancePlayer = 1
-- ally Nexus with Gamma
allianceEnemy = {}
allianceEnemy[0] = 1
-- ally Gamma with Nexus
allianceEnemy[1] = 3
-- TRUE if want enemies to use each others targets, otherwise mark FALSE
allianceFlag = false

-- Starting Enemy Power
-- starting power values for each enemy listed above
power = {}
power[0] = 20000
power[1] = 20000

-- Health Retreat Level for each of the enemies listed above
healthRetreat = {}
healthRetreat[0] = 80
-- default retreat for non-group units
healthRetreatX = {}
healthRetreatX[0] = 704
healthRetreatY = {}
healthRetreatY[0] = 6592
runOffFlag = true
healthRetreat[1] = 80
-- default retreat for non-group units
healthRetreatX[1] = 1728
healthRetreatY[1] = 1472

-- Structure Limits
-- MAX 5. Must be same as number of limits given next
numStrucStats = 6
strucStat = {}
strucStat[0] = "A0PowerGenerator"
-- 5
strucLimit = {}
strucLimit[0] = 4
strucStat[1] = "A0ResourceExtractor"
strucLimit[1] = 200
strucStat[2] = "A0ResearchFacility"
-- 5
strucLimit[2] = 4
strucStat[3] = "A0LightFactory"
-- 5
strucLimit[3] = 4
strucStat[4] = "A0CommandCentre"
strucLimit[4] = 1
strucStat[5] = "A0ComDroidControl"
strucLimit[5] = 1

-- Initialisation
-- starting view centre (in world units)
centreX = 7360
centreY = 15296
-- scroll limits (in tile units)
scrollX1 = 0
scrollY1 = 0
scrollX2 = 64
scrollY2 = 130
-- starting radar: 0=zoomed out, 2=zoomed in
zoomLevel = 0

-- MAX 8. Number of Landing zones/areas can't build on (0 = LZ)
numLZ = 3
-- coords of LZ in tile units
LZX = {}
LZX[0] = 56
LZY = {}
LZY[0] = 120

-- Nexus transport1 (east)
LZX[1] = 48
LZY[1] = 51
-- Nexus transport2 (west)
LZX[2] = 8
LZY[2] = 53

-- -1 for no reinforcements
ReinforceTime = -1
-- 30mins for rescue part!
timeLimit = 18000

-- Transport exit and entry
transX = {}
transX[0] = 57
transY = {}
transY[0] = 127
transX[1] = 57
transY[1] = 127

-- for each enemy that requires enemy transports landing (handled as a phantom factory)
-- define transport entry exit for each enemy!
entryX = {}
entryX[0] = 63
-- unnecessary if no enemy transports (defaults 0)
entryY = {}
entryY[0] = 4
-- leave as 0 if don't want a transport adding for this enemy
exitX = {}
exitX[0] = 63
exitY = {}
exitY[0] = 4

-- starting technology for enemy
-- NOTE: need to set first number in array for enemy player
-- second number needs to correspond to numTechs[enemy]
-- MAX 2 enemies, 10 technologies
numTechs = {}
numTechs[0] = 25
startTech = {}
startTech[0] = {}
startTech[0][0] = "R-Defense-WallUpgrade08"
startTech[0][1] = "R-Struc-Materials08"
startTech[0][2] = "R-Struc-Factory-Upgrade06"
startTech[0][3] = "R-Struc-Factory-Cyborg-Upgrade06"
startTech[0][4] = "R-Struc-VTOLFactory-Upgrade06"
startTech[0][5] = "R-Struc-VTOLPad-Upgrade06"
startTech[0][6] = "R-Vehicle-Engine09"
startTech[0][7] = "R-Vehicle-Metals06"
startTech[0][8] = "R-Cyborg-Metals07"
startTech[0][9] = "R-Vehicle-Armor-Heat05"
startTech[0][10] = "R-Cyborg-Armor-Heat05"
startTech[0][11] = "R-Sys-Engineering03"
startTech[0][12] = "R-Vehicle-Prop-Hover02"
startTech[0][13] = "R-Vehicle-Prop-VTOL02"
startTech[0][14] = "R-Wpn-Bomb-Accuracy03"
startTech[0][15] = "R-Wpn-Energy-Accuracy01"
startTech[0][16] = "R-Wpn-Energy-Damage01"
startTech[0][17] = "R-Wpn-Energy-ROF01"
startTech[0][18] = "R-Wpn-Missile-Accuracy01"
startTech[0][19] = "R-Wpn-Missile-Damage01"
startTech[0][20] = "R-Wpn-Rail-Damage02"
startTech[0][21] = "R-Wpn-Rail-ROF02"
startTech[0][22] = "R-Sys-Sensor-Upgrade01"
startTech[0][23] = "R-Sys-NEXUSrepair"
startTech[0][24] = "R-Wpn-Flamer-Damage06"

-- Briefings
-- MAX 5. Needs to be same as the number of briefings given next
numBriefs = 2
brief = {}
brief[0] = "MB3_B_MSG"
brief[1] = "MB3_B_MSG2"
-- brief[2]	INTMESSAGE	"MB3_B_MSG3"
-- 0 remove after playing, 1 keep, 2 don't play immediately
briefVal = {}
briefVal[0] = 0
-- 0 remove after playing, 1 keep, 2 don't play immediately
briefVal[1] = 1
-- briefVal[2]	int		0	//0 remove after playing, 1 keep, 2 don't play immediately
endMsg = "END"

-- Objectives
-- MAX 3. Needs to be the same as the number of objective blips given next
numObjectives = 1
objective = {}
objective[0] = "CM3B_GAMMABASE"
-- doesn't use index to array, use world coords
objectiveX = {}
objectiveX[0] = 1728
objectiveY = {}
objectiveY[0] = 1728

-- Victory Conditions
-- NOTE: always assumes victory condition of: number of artifacts collected = victoryArt
-- number of victory conditions to be met (not including artifacts)
numVictory = 1
-- DOESN'T need to be same as number given next (these are set TRUE/FALSE)
-- if victory condition required. Can have 2 set to TRUE and numVictory = 1
-- This will then let player win if EITHER condition is true!
-- Use numVictory of 0 if just want player to get artifacts

-- these now done as integers NOT bools!! Use -1 for False, # for True (often an index to check!)
-- for this reason must specify ALL victory[]!
-- all enemy vehicles and structures need to be killed
victory = {}
victory[0] = 1
-- all players vehicles at REGION index # (eg LZ REGION)
victory[1] = -1
-- number of objectives to get to (uses objective[0] to objective[#])
victory[2] = -1
-- number of bases to destroy (uses base[0] to base[#])
victory[3] = -1

-- Failure Conditions
-- Extra conditions above ALL player units and structures dead, or TIME LIMIT expired
-- Use -1 for False, # for True (often an index to check!)
-- group # index all got to REGION
fail = {}
fail[0] = -1
-- REGION index for above (these count as one condition!)
fail[1] = -1

-- Artifacts
-- number of artifacts required for victory (must be <= numArt)
victoryArt = 5
-- MAX 6. Number of artifacts in total (even if not in game, but added as extra research!)
numArt = 5

-- new improved way of doing artifacts
-- artType: 0 = artifact starts on map, 1 = get from STRUCTURE, 2 = get from FEATURE, 3 = get from DROID, 4 = at end of level
-- artVal: index to relevant type, ie FEATURE(crate), FEATURE, STRUCTURE, DROID
-- artX, artY: artifact coords (this is updated for DROIDS moving by script, but still needs an array to store them in!)
-- Gamma Base Research Fac
artType = {}
artType[0] = 1
artVal = {}
artVal[0] = 4
artX = {}
artX[0] = 2496
artY = {}
artY[0] = 1216
artComp = {}
artComp[0] = "R-Wpn-Mortar-Acc03"

-- Gamma Base Factory
artType[1] = 1
artVal[1] = 1
artX[1] = 960
artY[1] = 1088
artComp[1] = "R-Wpn-Cannon-ROF04"

-- East LZ BeamLaser tower
artType[2] = 1
artVal[2] = 0
-- 6720
artX[2] = 6336
-- 6464
artY[2] = 6848
artComp[2] = "R-Wpn-Laser01"

-- Nexus HQ (West)
artType[3] = 1
artVal[3] = 5
artX[3] = 704
artY[3] = 6976
artComp[3] = "R-Struc-Research-Upgrade07"

-- Gamma HQ
artType[4] = 1
artVal[4] = 6
artX[4] = 2240
artY[4] = 960
artComp[4] = "R-Vehicle-Body03"

-- lists of stuff referred to by index number
-- ********************************************

-- ********************************************
-- FEATURES (inc crates, by ID number)	MAX = 10
-- features	[0]	FEATURE		649		//crate artifact (1st in valley)
-- features	[1]	FEATURE		661		//crate artifact (2nd by huts) (CHANGED TO BUNKER)

-- ********************************************
-- STRUCTURES (by ID number)		MAX = 10
-- BeamLaser tower (artifact)
structures = {}
structures[0] = getStructureByID(1181)
-- Gamma base factory
structures[1] = getStructureByID(432)
-- Gamma base cyborg Factory 1
structures[2] = getStructureByID(134)
-- structures	[3]	STRUCTURE	135		//Gamma base cyborg Factory 2
-- Gamma base Research Fac (artifact)
structures[4] = getStructureByID(143)
-- Nexus HQ(artifact)
structures[5] = getStructureByID(1180)
-- Gamma HQ(artifact)
structures[6] = getStructureByID(133)

-- ********************************************
-- DROIDS (by ID number)		MAX = 10
-- droids		[0]	DROID		3279		//testdroid

-- ********************************************
-- list of templates (by name)		 MAX = 20
-- ********************************************
-- gamma base templates  - (use player technology) [NEXUS TECH FOR NOW! It's a Cam# thing]
templates = {}
templates[0] = "NX-M-Missile-A-T-Hover"
templates[1] = "NX-M-Rail2-Hover"
templates[2] = "NX-M-Missile-A-T-Hover"
-- templates	[3]	TEMPLATE	"NX-M-Rail2-Hover"

-- gamma base cyborg factories
templates[4] = "NX-Cyb-Rail1-JUMP"
templates[5] = "NX-Cyb-PulseLas-JUMP"
templates[6] = "NX-Cyb-Miss-JUMP"

-- base 4 medium factory templates & transport 1
templates[7] = "NX-Cyb-Rail1-JUMP"
templates[8] = "NX-Cyb-PulseLas-JUMP"
templates[9] = "NX-M-HvSam-Hover"
templates[10] = "NX-M-Rail2-Hover"

-- transport 2 cyborgs
templates[11] = "NX-Cyb-Rail1-JUMP"
templates[12] = "NX-Cyb-PulseLas-JUMP"
templates[13] = "NX-M-HvSam-Hover"
templates[14] = "NX-M-Link-Hover"

-- edgemap units
templates[15] = "NX-Cyb-Rail1-JUMP"
templates[16] = "NX-Cyb-PulseLas-JUMP"
templates[17] = "NX-Cyb-Miss-JUMP"
templates[18] = "NX-M-Link-Hover"


-- ********************************************
-- coordinates (world coords)		MAX = 10
-- ********************************************

-- retreat point (East Trans1)
coordsX = {}
coordsX[0] = 6464
coordsY = {}
coordsY[0] = 7104

-- edge map factory
coordsX[1] = 64
coordsY[1] = 10816

-- retreat point (West Trans1)
coordsX[2] = 704
coordsY[2] = 6592
-- NE corner of lake
coordsX[3] = 5952
coordsY[3] = 1856
-- Gamma Base
coordsX[4] = 1728
coordsY[4] = 1472
-- North end of pass
coordsX[5] = 2496
coordsY[5] = 6080

-- South of ridge
coordsX[6] = 4416
coordsY[6] = 9152
-- West ridge
coordsX[7] = 3520
coordsY[7] = 6336
-- East ridge
coordsX[8] = 5696
coordsY[8] = 7488

-- west door to player base
coordsX[9] = 6080
coordsY[9] = 14144
-- east door to player base
coordsX[10] = 6592
coordsY[10] = 11456
-- Player's LZ
coordsX[11] = 7232
coordsY[11] = 14656

-- ********************************************
-- regions (world coords)		MAX = 20
-- ********************************************
-- north pass trigger zone
regionsX1 = {}
regionsX1[0] = 2368
regionsY1 = {}
regionsY1[0] = 6592
regionsX2 = {}
regionsX2[0] = 4160
regionsY2 = {}
regionsY2[0] = 8384

-- Gmma base area to protect
regionsX1[1] = 448
regionsY1[1] = 448
regionsX2[1] = 2880
regionsY2[1] = 3648

-- enemy transport1 blip (east)
regionsX1[2] = 5696
regionsY1[2] = 4800
regionsX2[2] = 7360
regionsY2[2] = 7872

-- enemy transport2 blip (west)
regionsX1[3] = 448
regionsY1[3] = 5440
regionsX2[3] = 1600
regionsY2[3] = 7104

-- this region needs to be the same as in Cam3BX regions[0] since trap trigger
-- 440			// enemy/player gamma base
regionsX1[4] = 448
-- 576
regionsY1[4] = 448
-- 3008
regionsX2[4] = 2880
-- 3776
regionsY2[4] = 3648

-- transport 1 group east
regionsX1[5] = 6080
regionsY1[5] = 5568
regionsX2[5] = 6848
regionsY2[5] = 6080

-- transport 2 group west
regionsX1[6] = 192
regionsY1[6] = 4288
regionsX2[6] = 1472
regionsY2[6] = 6336


-- ********************************************
-- Enemy Base Blips
-- ********************************************
-- MAX = 5. Must be same as number of bases listed next
numBases = 2

basePlayer = {}
basePlayer[0] = 0
baseMsg = {}
baseMsg[0] = "CM3B_TRANS1"
baseRegion = {}
baseRegion[0] = 2
baseWav1 = {}
baseWav1[0] = 0
-- index to baseSnd	Eradicated
baseWav2 = {}
baseWav2[0] = 3

-- do radar as a base
basePlayer[1] = 0
baseMsg[1] = "CM3B_TRANS2"
baseRegion[1] = 3
baseWav1[1] = 0
baseWav2[1] = 3


-- ********************************************
-- Enemy Groups
-- ********************************************
-- group MAX = 10
numGroups = 3

-- transport 1 group (east)
-- 1		//0 = Ambush/Patrol, 1 = Defence, 2 = Scout, 3 = Attack...
grpType = {}
grpType[0] = 0
-- player number enemy[0]
grpPlayer = {}
grpPlayer[0] = 0
-- index in regions array to define group
grpRegion = {}
grpRegion[0] = 5
-- 30mins. (always make >= 0 for defence forces)
grpTimeGo = {}
grpTimeGo[0] = 181
-- index into regions to protect (usually a base blip region)
grpRegionGo = {}
grpRegionGo[0] = 4
-- player number to cross trigger region (may not need?)
grpWhoGo = {}
grpWhoGo[0] = 0
-- don't set morale/leadership/retreat
grpMorale = {}
grpMorale[0] = 90
-- leadership value
grpLeadership = {}
grpLeadership[0] = 0
-- retreat to base 1 assembly
grpRetreatXY = {}
grpRetreatXY[0] = 0
-- index in coords/sectors array (depends on grpType)
grpPosStart = {}
grpPosStart[0] = 7
-- Minimum index in coords array
grpPosMin = {}
grpPosMin[0] = 5
-- Maximum index in coords array
grpPosMax = {}
grpPosMax[0] = 8
-- Step increase for next 'waypoint'
grpPosStep = {}
grpPosStep[0] = 1
-- 0 = stop, 1 = loop, 2 = pingpong, 3 = random thru waypoints
grpPosType = {}
grpPosType[0] = 3
-- index factory to reinforce group. -1 = any factory.
grpFactory = {}
grpFactory[0] = 2
-- ideal size. If less than this factory will reinforce
grpIdealSize = {}
grpIdealSize[0] = 10

-- transport 2 group (west)
-- 1	//0 = Ambush/Patrol, 1 = Defence, 2 = Scout, 3 = Attack...
grpType[1] = 0
-- player number (NP)
grpPlayer[1] = 0
-- index in regions array
grpRegion[1] = 6
-- 30mins time trigger (always make >= 0 for defence forces)
grpTimeGo[1] = 180
-- index into regions to protect (usually a base blip region)
grpRegionGo[1] = 4
-- player number to cross trigger region (may not need?)
grpWhoGo[1] = 0
-- very timid! morale = 1%
grpMorale[1] = 90
-- leadership value
grpLeadership[1] = 0
-- retreat (index in coords array) base1 assembly
grpRetreatXY[1] = 2
-- index in sectors array (depends on grpType)
grpPosStart[1] = 11
-- Minimum index in coords array
grpPosMin[1] = 9
-- Maximum index in coords array
grpPosMax[1] = 11
-- Step increase for next 'waypoint'
grpPosStep[1] = 1
-- 0 = stop, 1 = loop, 2 = pingpong, 3 = random thru waypoints
grpPosType[1] = 3
-- index structure to reinforce group. -1 = any factory.
grpFactory[1] = 3
-- ideal size. If less than this factory will reinforce
grpIdealSize[1] = 10


-- Gamma defenders
-- 0 = Ambush/Patrol, 1 = Defence, 2 = Scout, 3 = Attack...
grpType[2] = 1
-- player number (Gamma base)
grpPlayer[2] = 1
-- index in regions array
grpRegion[2] = 4
-- 30mins time trigger (always make >= 0 for defence forces)
grpTimeGo[2] = 179
-- area to defend (base)
grpRegionGo[2] = 1
-- player number to cross trigger region (may not need?)
grpWhoGo[2] = 0
-- very timid! morale = 1%
grpMorale[2] = 90
-- leadership value
grpLeadership[2] = 0
-- retreat (index in coords array) base1 assembly
grpRetreatXY[2] = 4
-- index in sectors array (depends on grpType)
grpPosStart[2] = 5
-- Minimum index in coords array
grpPosMin[2] = 4
-- Maximum index in coords array
grpPosMax[2] = 5
-- Step increase for next 'waypoint'
grpPosStep[2] = 1
-- 0 = stop, 1 = loop, 2 = pingpong, 3 = random thru waypoints
grpPosType[2] = 2
-- index structure to reinforce group. -1 = any factory.
grpFactory[2] = -1
-- ideal size. If less than this factory will reinforce
grpIdealSize[2] = 10

-- Factories
-- MAX = 10
numFactories = 4


-- gamma base large factory
-- index to structures
factID = {}
factID[0] = 1
-- 30minindex to assembly point. -1 for don't set
factAssXY = {}
factAssXY[0] = -1
-- delay before starting production in 10s
factTimeGo = {}
factTimeGo[0] = 181
-- trap region for trigger (assume WhoGo = 0)
factRegionGo = {}
factRegionGo[0] = 4
-- index to starting template
factTempMin = {}
factTempMin[0] = 0
-- index to maximum template
factTempMax = {}
factTempMax[0] = 2
-- 15mins .Time in 10s for factory to try to produce again
factEvery = {}
factEvery[0] = 90

-- gamma base cyborg factory 1
-- index to structures
factID[1] = 2
-- index to assembly point. -1 for don't set
factAssXY[1] = -1
-- 31mindelay before starting production in 10s
factTimeGo[1] = 186
-- trap region for trigger (assume WhoGo = 0)
factRegionGo[1] = 4
-- index to starting template
factTempMin[1] = 4
-- index to maximum template
factTempMax[1] = 6
-- 10mins .Time in 10s for factory to try to produce again
factEvery[1] = 60


-- transport 1 (East)
-- phantom factory, uses transport
factID[2] = -2
-- index to LZs (point to correct one for enemy number, eg 2 for player 2 Collective)
factAssXY[2] = 1
-- 31mindelay before starting production in 10s
factTimeGo[2] = 186
-- -1		//trap region to trigger transport
factRegionGo[2] = 4
-- index to starting template
factTempMin[2] = 7
-- index to maximum template
factTempMax[2] = 10
-- 25 mins .Time in 10s for factory to produce again
factEvery[2] = 150

-- transport 2 (West)
-- phantom factory, uses transport
factID[3] = -2
-- index to LZs (point to correct one for enemy number, eg 2 for player 2 Collective)
factAssXY[3] = 2
-- 30mindelay before starting production in 10s
factTimeGo[3] = 181
-- trap region to trigger transport
factRegionGo[3] = 4
-- index to starting template
factTempMin[3] = 11
-- index to maximum template
factTempMax[3] = 14
-- 30 mins .Time in 10s for factory to produce again
factEvery[3] = 180

-- 'Globals'
-- These should be same in each file, but may need slight alterations
-- player's player number
player = 0
crate = "Crate"
-- 171				//range to artifact about 1.5 tiles
artRange = 200
-- range to objective 5 Tiles
objectiveRange = 640
-- range to waypoint 2ish tiles
wayRange = 300
-- range for target spotting
targetRange = 768
-- maximum number of targets to store for each enemy
targetMax = 4
-- mission failed
lostSnd = "pcv470.ogg"
-- Base Under Attack
attackSnd1 = "pcv337.ogg"
-- artifact sounds
artSnd1 = "pcv351.ogg"
artSnd2 = "pcv352.ogg"
-- for enemy transports
transporter = "Transporter"
-- enemy transport landing
transSnd = "pcv381.ogg"
LZComp = "pcv445.ogg"
LZClear = "lz-clear.ogg"

-- base WAVs. MAX = 5
-- Enemy Base Detected
baseSnd = {}
baseSnd[0] = "pcv379.ogg"
-- Enemy Base Detected
baseSnd[1] = "pcv379.ogg"
-- Enemy Base Detected
baseSnd[2] = "pcv379.ogg"
-- Enemy base eradicated
baseSnd[3] = "pcv394.ogg"

--run the code
dofile('genexp_logic.lua')
