-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "tech.slo"

-- cam3tech.vlo
-- set up starting technology, templates etc. for GAMMA player at the start of a campaign

-- ALPHA BASE player
player = 1
numTechs = 39
startTech = {}
startTech[0] = "R-Wpn-Cannon-Accuracy02"
startTech[1] = "R-Wpn-Cannon-Damage06"
startTech[2] = "R-Wpn-Cannon-ROF03"
startTech[3] = "R-Wpn-Flamer-Damage06"
startTech[4] = "R-Wpn-Flamer-ROF03"
startTech[5] = "R-Wpn-Howitzer-Accuracy02"
startTech[6] = "R-Wpn-Howitzer-Damage03"
startTech[7] = "R-Wpn-MG-Damage07"
startTech[8] = "R-Wpn-MG-ROF03"
startTech[9] = "R-Wpn-Mortar-Acc02"
startTech[10] = "R-Wpn-Mortar-Damage06"
startTech[11] = "R-Wpn-Mortar-ROF03"
startTech[12] = "R-Wpn-Rocket-Accuracy02"
startTech[13] = "R-Wpn-Rocket-Damage06"
startTech[14] = "R-Wpn-Rocket-ROF03"
startTech[15] = "R-Wpn-RocketSlow-Accuracy03"
startTech[16] = "R-Wpn-RocketSlow-Damage06"
startTech[17] = "R-Wpn-RocketSlow-ROF03"
startTech[18] = "R-Vehicle-Armor-Heat02"
startTech[19] = "R-Vehicle-Engine06"
startTech[20] = "R-Vehicle-Metals06"
startTech[21] = "R-Cyborg-Metals06"
startTech[22] = "R-Cyborg-Armor-Heat02"
startTech[23] = "R-Defense-WallUpgrade06"
startTech[24] = "R-Struc-Factory-Upgrade06"
startTech[25] = "R-Struc-Factory-Cyborg-Upgrade06"
startTech[26] = "R-Struc-VTOLFactory-Upgrade03"
startTech[27] = "R-Struc-VTOLPad-Upgrade03"
startTech[28] = "R-Struc-Materials06"
startTech[29] = "R-Struc-Power-Upgrade01"
startTech[30] = "R-Struc-Research-Upgrade06"
startTech[31] = "R-Struc-RprFac-Upgrade06"
startTech[32] = "R-Sys-Engineering02"
startTech[33] = "R-Sys-MobileRepairTurret01"
startTech[34] = "R-Sys-Sensor-Upgrade01"
startTech[35] = "R-Wpn-AAGun-Accuracy02"
startTech[36] = "R-Wpn-AAGun-Damage03"
startTech[37] = "R-Wpn-AAGun-ROF03"
startTech[38] = "R-Wpn-Bomb-Accuracy02"

numStructs = 40
startStruct = {}
startStruct[0] = "A0ComDroidControl"
startStruct[1] = "A0CommandCentre"
startStruct[2] = "A0CyborgFactory"
startStruct[3] = "A0FacMod1"
startStruct[4] = "A0HardcreteMk1CWall"
startStruct[5] = "A0HardcreteMk1Wall"
startStruct[6] = "A0LightFactory"
startStruct[7] = "A0PowerGenerator"
startStruct[8] = "A0PowMod1"
startStruct[9] = "A0RepairCentre3"
startStruct[10] = "A0ResearchFacility"
startStruct[11] = "A0ResearchModule1"
startStruct[12] = "A0ResourceExtractor"
startStruct[13] = "A0TankTrap"
startStruct[14] = "TankTrapC"
startStruct[15] = "A0VTolFactory1"
startStruct[16] = "A0VtolPad"
startStruct[17] = "Sys-CB-Tower01"
startStruct[18] = "Sys-SensoTower02"
startStruct[19] = "Sys-VTOL-CB-Tower01"
startStruct[20] = "Sys-VTOL-RadarTower01"
startStruct[21] = "AASite-QuadBof"
startStruct[22] = "AASite-QuadRotMg"
startStruct[23] = "Emplacement-HPVcannon"
startStruct[24] = "Emplacement-Howitzer105"
startStruct[25] = "Emplacement-Howitzer150"
startStruct[26] = "Emplacement-Rocket06-IDF"
startStruct[27] = "Emplacement-MortarPit02"
startStruct[28] = "Emplacement-RotMor"
startStruct[29] = "Emplacement-MRL-pit"
startStruct[30] = "Emplacement-Rocket06-IDF"
startStruct[31] = "Emplacement-HvyATrocket"
startStruct[32] = "PillBox6"
startStruct[33] = "Wall-RotMg"
startStruct[34] = "Wall-VulcanCan"
startStruct[35] = "WallTower04"
startStruct[36] = "WallTower-HvATrocket"
startStruct[37] = "WallTower-HPVcannon"
-- Inferno Emplacement
startStruct[38] = "Tower-Projector"
startStruct[39] = "Pillbox-RotMG"

numWeapons = 36
startWeapon = {}
startWeapon[0] = getWeapon("AAGun2Mk1")
startWeapon[1] = getWeapon("Bomb1-VTOL-LtHE")
startWeapon[2] = getWeapon("Bomb2-VTOL-HvHE")
startWeapon[3] = getWeapon("Bomb3-VTOL-LtINC")
startWeapon[4] = getWeapon("Bomb4-VTOL-HvyINC")
startWeapon[5] = getWeapon("Cannon1-VTOL")
startWeapon[6] = getWeapon("Cannon1Mk1")
startWeapon[7] = getWeapon("Cannon375mmMk1")
startWeapon[8] = getWeapon("Cannon4AUTO-VTOL")
startWeapon[9] = getWeapon("Cannon4AUTOMk1")
startWeapon[10] = getWeapon("Cannon5Vulcan-VTOL")
startWeapon[11] = getWeapon("Cannon5VulcanMk1")
startWeapon[12] = getWeapon("Flame2")
startWeapon[13] = getWeapon("Howitzer105Mk1")
startWeapon[14] = getWeapon("Howitzer150Mk1")
startWeapon[15] = getWeapon("MG4ROTARY-VTOL")
startWeapon[16] = getWeapon("MG4ROTARYMk1")
startWeapon[17] = getWeapon("Mortar3ROTARYMk1")
startWeapon[18] = getWeapon("Rocket-BB")
startWeapon[19] = getWeapon("Rocket-HvyA-T")
startWeapon[20] = getWeapon("Rocket-IDF")
startWeapon[21] = getWeapon("Rocket-LtA-T")
startWeapon[22] = getWeapon("Rocket-VTOL-BB")
startWeapon[23] = getWeapon("Rocket-VTOL-HvyA-T")
startWeapon[24] = getWeapon("Rocket-VTOL-LtA-T")
startWeapon[25] = getWeapon("Rocket-VTOL-Pod")
startWeapon[26] = getWeapon("Cannon4AUTO-VTOL")
startWeapon[27] = getWeapon("Cannon5Vulcan-VTOL")
startWeapon[28] = getWeapon("MG4ROTARY-VTOL")
startWeapon[29] = getWeapon("Rocket-VTOL-BB")
startWeapon[30] = getWeapon("Rocket-VTOL-HvyA-T")
startWeapon[31] = getWeapon("QuadRotAAGun")
startWeapon[32] = getWeapon("Rocket-MRL")
startWeapon[33] = getWeapon("Rocket-Pod")
startWeapon[34] = getWeapon("Rocket-VTOL-Pod")
startWeapon[35] = getWeapon("Mortar2Mk1")

numBodies = 13
startBody = {}
startBody[0] = "Body11ABT"
startBody[1] = "Body12SUP"
startBody[2] = "Body1REC"
startBody[3] = "Body2SUP"
startBody[4] = "Body4ABT"
startBody[5] = "Body5REC"
startBody[6] = "Body6SUPP"
startBody[7] = "Body8MBT"
startBody[8] = "Body9REC"
startBody[9] = "CyborgCannonGrd"
startBody[10] = "CyborgFlamerGrd"
startBody[11] = "CybRotMgGrd"
startBody[12] = "CyborgRkt1Ground"

numProps = 5
startProp = {}
startProp[0] = "HalfTrack"
startProp[1] = "hover01"
startProp[2] = "tracked01"
startProp[3] = "V-Tol"
startProp[4] = "wheeled01"

numConstructs = 1
startConstruct = {}
startConstruct[0] = "Spade1Mk1"

numSensors = 4
startSensor = {}
startSensor[0] = "SensorTurret1Mk1"
startSensor[1] = "Sys-CBTurret01"
startSensor[2] = "Sys-VstrikeTurret01"
startSensor[3] = "Sys-VTOLCBTurret01"

numECMs = 0
-- startECM	[0]	ECM		""

numRepairs = 1
startRepair = {}
startRepair[0] = "LightRepair1"

numBrains = 1
startBrain = {}
startBrain[0] = "CommandBrain01"

numResearch = 2
startResearch = {}
startResearch[0] = "R-Wpn-Howitzer03-Rot"
startResearch[1] = "R-Wpn-MG-Damage08"

--run the code
dofile('tech_logic.lua')
