-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "GenExp.slo"

-- Generic VLO file template for start/expand levels

-- Cam3c.vlo

-- Next level stuff
-- points to next level
NextLev = "CAM3A-D1"

-- Define Players/Enemies
-- MAX 2. Must define same as number of enemy players given next
numEnemies = 1
enemy = {}
enemy[0] = 3
-- ally player with self (could be a different player number
alliancePlayer = 0
-- ally enemy with self (could be a different player number
allianceEnemy = {}
allianceEnemy[0] = 3
-- TRUE if want enemies to use each others targets, otherwise mark FALSE
allianceFlag = false

-- Starting Enemy Power
-- starting power values for each enemy listed above
power = {}
power[0] = 50000
-- power[1]	int		1000

-- Health Retreat Level for each of the enemies listed above
healthRetreat = {}
healthRetreat[0] = 80
-- default retreat for non-group units
healthRetreatX = {}
healthRetreatX[0] = 6848
healthRetreatY = {}
healthRetreatY[0] = 23232
runOffFlag = true

-- Structure Limits
-- MAX 5. Must be same as number of limits given next
numStrucStats = 6
strucStat = {}
strucStat[0] = "A0PowerGenerator"
-- 5
strucLimit = {}
strucLimit[0] = 0
strucStat[1] = "A0ResourceExtractor"
-- 200
strucLimit[1] = 0
strucStat[2] = "A0ResearchFacility"
-- 5
strucLimit[2] = 0
strucStat[3] = "A0LightFactory"
-- 5
strucLimit[3] = 0
strucStat[4] = "A0CommandCentre"
-- 1
strucLimit[4] = 0
strucStat[5] = "A0ComDroidControl"
-- 1
strucLimit[5] = 0

-- Initialisation
-- 960	//starting view centre (in world units)
centreX = 704
-- 17344
centreY = 17856
-- scroll limits (in tile units)
scrollX1 = 0
scrollY1 = 0
scrollX2 = 64
scrollY2 = 192
-- starting radar: 0=zoomed out, 2=zoomed in
zoomLevel = 1

-- 2	//MAX 8. Number of Landing zones/areas can't build on (0 = LZ)
numLZ = 1
-- coords of LZ in tile units
LZX = {}
LZX[0] = 56
LZY = {}
LZY[0] = 120
--[[LZX[1]		int		9	//coords of Gamma base LZ in tile units
LZY[1]		int		184]]--

-- -1 for no reinforcements
ReinforceTime = -1
-- 10mins for first part (needs to be done if previous misison had a time limit!)
timeLimit = 6000

-- Transport exit and entry
transX = {}
transX[0] = 57
transY = {}
transY[0] = 127
transX[1] = 57
transY[1] = 127

-- starting technology for enemy
-- NOTE: need to set first number in array for enemy player
-- second number needs to correspond to numTechs[enemy]
-- MAX 2 enemies, 10 technologies
numTechs = {}
numTechs[0] = 25
startTech = {}
startTech[0] = {}
startTech[0][0] = "R-Defense-WallUpgrade09"
startTech[0][1] = "R-Struc-Materials09"
startTech[0][2] = "R-Struc-Factory-Upgrade06"
startTech[0][3] = "R-Struc-Factory-Cyborg-Upgrade06"
startTech[0][4] = "R-Struc-VTOLFactory-Upgrade06"
startTech[0][5] = "R-Struc-VTOLPad-Upgrade06"
startTech[0][6] = "R-Vehicle-Engine09"
startTech[0][7] = "R-Vehicle-Metals07"
startTech[0][8] = "R-Cyborg-Metals08"
startTech[0][9] = "R-Vehicle-Armor-Heat05"
startTech[0][10] = "R-Cyborg-Armor-Heat05"
startTech[0][11] = "R-Sys-Engineering03"
startTech[0][12] = "R-Vehicle-Prop-Hover02"
startTech[0][13] = "R-Vehicle-Prop-VTOL02"
startTech[0][14] = "R-Wpn-Bomb-Accuracy03"
startTech[0][15] = "R-Wpn-Energy-Accuracy01"
startTech[0][16] = "R-Wpn-Energy-Damage03"
startTech[0][17] = "R-Wpn-Energy-ROF03"
startTech[0][18] = "R-Wpn-Missile-Accuracy01"
startTech[0][19] = "R-Wpn-Missile-Damage02"
startTech[0][20] = "R-Wpn-Rail-Damage02"
startTech[0][21] = "R-Wpn-Rail-ROF02"
startTech[0][22] = "R-Sys-Sensor-Upgrade01"
startTech[0][23] = "R-Sys-NEXUSrepair"
startTech[0][24] = "R-Wpn-Flamer-Damage06"

-- Briefings
-- MAX 5. Needs to be same as the number of briefings given next
numBriefs = 2
brief = {}
brief[0] = "MB3_C_MSG"
brief[1] = "MB3_C_MSG2"
-- brief[2]	INTMESSAGE	"MB3_C_MSG3"
-- 0 remove after playing, 1 keep, 2 don't play immediately
briefVal = {}
briefVal[0] = 0
-- 0 remove after playing, 1 keep, 2 don't play immediately
briefVal[1] = 1
-- briefVal[2]	int		1	//0 remove after playing, 1 keep, 2 don't play immediately
endMsg = "END"

-- Objectives
-- MAX 3. Needs to be the same as the number of objective blips given next
numObjectives = 1

objective = {}
objective[0] = "CM3C_GAMMABASE"
-- doesn't use index to array, use world coords
objectiveX = {}
objectiveX[0] = 1472
objectiveY = {}
objectiveY[0] = 23104

-- Victory Conditions
-- NOTE: always assumes victory condition of: number of artifacts collected = victoryArt
-- number of victory conditions to be met (not including artifacts)
numVictory = 1
-- DOESN'T need to be same as number given next (these are set TRUE/FALSE)
-- if victory condition required. Can have 2 set to TRUE and numVictory = 1
-- This will then let player win if EITHER condition is true!
-- Use numVictory of 0 if just want player to get artifacts

-- these now done as integers NOT bools!! Use -1 for False, # for True (often an index to check!)
-- for this reason must specify ALL victory[]!
-- all enemy vehicles and structures need to be killed
victory = {}
victory[0] = 1
-- all players vehicles at REGION index # (eg LZ REGION)
victory[1] = -1
-- number of objectives to get to (uses objective[0] to objective[#])
victory[2] = -1
-- number of bases to destroy (uses base[0] to base[#])
victory[3] = -1
-- team beta at Gamma Base
linkVictory = true

-- Failure Conditions
-- Extra conditions above ALL player units and structures dead, or TIME LIMIT expired
-- Use -1 for False, # for True (often an index to check!)
-- group # index all got to REGION
fail = {}
fail[0] = -1
-- REGION index for above (these count as one condition!)
fail[1] = -1
-- team Beta dead before reaching base
linkFail = true

-- Artifacts
-- number of artifacts required for victory (must be <= numArt)
victoryArt = 4
-- MAX 6. Number of artifacts in total (even if not in game, but added as extra research!)
numArt = 4

-- new improved way of doing artifacts
-- artType: 0 = artifact starts on map, 1 = get from STRUCTURE, 2 = get from FEATURE, 3 = get from DROID, 4 = at end of level
-- artVal: index to relevant type, ie FEATURE(crate), FEATURE, STRUCTURE, DROID
-- artX, artY: artifact coords (this is updated for DROIDS moving by script, but still needs an array to store them in!)

-- VTOL factory
artType = {}
artType[0] = 1
artVal = {}
artVal[0] = 2
artX = {}
artX[0] = 4544
artY = {}
artY[0] = 21952
artComp = {}
artComp[0] = "R-Struc-VTOLFactory-Upgrade04"

-- Factory
artType[1] = 1
artVal[1] = 0
artX[1] = 7232
artY[1] = 22976
artComp[1] = "R-Vehicle-Body07"

-- HQ
artType[2] = 1
artVal[2] = 4
artX[2] = 6720
artY[2] = 23616
artComp[2] = "R-Wpn-Missile-LtSAM"

-- Cyborg Factory
artType[3] = 1
artVal[3] = 1
artX[3] = 3776
artY[3] = 17088
artComp[3] = "R-Wpn-RailGun01"

-- ********************************************

-- ********************************************
-- FEATURES (inc crates, by ID number)	MAX = 10
-- features	[0]	FEATURE		649		//crate artifact (1st in valley)
-- features	[1]	FEATURE		661		//crate artifact (2nd by huts) (CHANGED TO BUNKER)

-- ********************************************
-- STRUCTURES (by ID number)		MAX = 10

-- 669		//Base 1 Heavy Factory (artifact)
structures = {}
structures[0] = getStructureByID(1309)
-- Northern Cyborg Factory (artifact)
structures[1] = getStructureByID(690)
-- Mid VTOL Factory	(artifact) //different script to handle this
structures[2] = getStructureByID(544)
-- Southern Cyborg Factory
structures[3] = getStructureByID(529)
-- HQ (artifact)
structures[4] = getStructureByID(1256)

-- ********************************************
-- DROIDS (by ID number)		MAX = 10
-- droids		[0]	DROID		3279		//testdroid

-- ********************************************
-- list of templates (by name)		 MAX = 20
-- ********************************************
templates = {}
templates[0] = "NX-Cyb-Rail1-JUMP"
templates[1] = "NX-Cyb-Miss-JUMP"
templates[2] = "NX-Cyb-PulseLas-JUMP"

templates[3] = "NX-M-Rail2-Hover"
templates[4] = "NX-L-Flash-Hover"
templates[5] = "NX-M-HvSam-Hover"
templates[6] = "NX-M-Link-Hover"


-- ********************************************
-- coordinates (world coords)		MAX = 10
-- ********************************************

-- Default retreat to south base
coordsX = {}
coordsX[0] = 6848
coordsY = {}
coordsY[0] = 23232

-- South of VTOL factory
coordsX[1] = 4416
coordsY[1] = 23232
-- NW ramp to gamma
coordsX[2] = 1600
coordsY[2] = 18752
-- Gamma base
coordsX[3] = 1600
coordsY[3] = 18752

-- Eastern ridge of gamma base
coordsX[4] = 2112
coordsY[4] = 22208


-- ********************************************
-- regions (world coords)		MAX = 20
-- ********************************************
-- group 0 NE
regionsX1 = {}
regionsX1[0] = 6848
regionsY1 = {}
regionsY1[0] = 18112
regionsX2 = {}
regionsX2[0] = 7232
regionsY2 = {}
regionsY2[0] = 18752

-- group 1 E
regionsX1[1] = 6720
regionsY1[1] = 20928
regionsX2[1] = 7232
regionsY2[1] = 21440

-- Gamma base trigger region
regionsX1[2] = 192
regionsY1[2] = 22208
regionsX2[2] = 2368
regionsY2[2] = 24256

-- North base blip
regionsX1[3] = 3008
regionsY1[3] = 16320
regionsX2[3] = 4672
regionsY2[3] = 18880
-- Mid VTOL base blip
regionsX1[4] = 3008
regionsY1[4] = 19776
regionsX2[4] = 5568
regionsY2[4] = 22976
-- South base blip
regionsX1[5] = 5568
regionsY1[5] = 21952
regionsX2[5] = 8000
regionsY2[5] = 24896

-- ********************************************
-- sector Stuff
-- ********************************************
-- sectors to attack (covers 1A-C expansion area, in order of priority to attack)
-- MAX = 20
-- 3C SE Quad
sectorsX1 = {}
sectorsX1[0] = 4096
sectorsY1 = {}
sectorsY1[0] = 20480
sectorsX2 = {}
sectorsX2[0] = 8000
sectorsY2 = {}
sectorsY2[0] = 24384
-- 3C SW Quad
sectorsX1[1] = 64
sectorsY1[1] = 20480
sectorsX2[1] = 4096
sectorsY2[1] = 24384
-- 3C NW Quad
sectorsX1[2] = 64
sectorsY1[2] = 16384
sectorsX2[2] = 4096
sectorsY2[2] = 20480
-- 3C NE Quad
sectorsX1[3] = 4096
sectorsY1[3] = 16384
sectorsX2[3] = 8000
sectorsY2[3] = 20480
-- 3A SW Quad
sectorsX1[4] = 64
sectorsY1[4] = 12288
sectorsX2[4] = 4096
sectorsY2[4] = 16384
-- 3A SE Quad
sectorsX1[5] = 4096
sectorsY1[5] = 12288
sectorsX2[5] = 8000
sectorsY2[5] = 16384
-- 3A NE Quad
sectorsX1[6] = 4096
sectorsY1[6] = 8192
sectorsX2[6] = 8000
sectorsY2[6] = 12288
-- 3A NW Quad
sectorsX1[7] = 64
sectorsY1[7] = 8192
sectorsX2[7] = 4096
sectorsY2[7] = 12288
-- 3B SW Quad
sectorsX1[8] = 64
sectorsY1[8] = 4096
sectorsX2[8] = 4096
sectorsY2[8] = 8192
-- 3B NW Quad
sectorsX1[9] = 64
sectorsY1[9] = 64
sectorsX2[9] = 4096
sectorsY2[9] = 4096
-- 3B NE Quad
sectorsX1[10] = 4096
sectorsY1[10] = 64
sectorsX2[10] = 8000
sectorsY2[10] = 4096
-- 3B SE Quad
sectorsX1[11] = 4096
sectorsY1[11] = 4096
sectorsX2[11] = 8000
sectorsY2[11] = 8192


-- ********************************************
-- Enemy Base Blips
-- ********************************************
-- MAX = 5. Must be same as number of bases listed next
numBases = 3

-- enemy player number who owns base
basePlayer = {}
basePlayer[0] = 0
-- enemy base blip message (prox.txt)
baseMsg = {}
baseMsg[0] = "CM3C_BASE1"
-- index to regions
baseRegion = {}
baseRegion[0] = 0
baseWav1 = {}
baseWav1[0] = 0
-- index to baseSnd	Eradicated
baseWav2 = {}
baseWav2[0] = 3

basePlayer[1] = 0
baseMsg[1] = "CM3C_BASE2"
baseRegion[1] = 1
-- index to baseSnd	enemy detected
baseWav1[1] = 0
-- index to baseSnd	Eradicated
baseWav2[1] = 3

basePlayer[2] = 0
baseMsg[2] = "CM3C_BASE3"
baseRegion[2] = 2
baseWav1[2] = 0
-- index to baseSnd	Eradicated
baseWav2[2] = 3

-- ********************************************
-- Enemy Groups
-- ********************************************
-- group MAX = 10
numGroups = 3

-- NorthEast Cyborgs
-- 0 = Ambush/Patrol, 1 = Defence, 2 = Scout, 3 = Attack...
grpType = {}
grpType[0] = 0
-- player number (NP)
grpPlayer = {}
grpPlayer[0] = 0
-- index in regions array
grpRegion = {}
grpRegion[0] = 0
-- 5mins. (always make >= 0 for defence forces)
grpTimeGo = {}
grpTimeGo[0] = 30
-- gamma base region for trigger (assume WhoGo = 0)
grpRegionGo = {}
grpRegionGo[0] = 2
-- player number to cross trigger region (may not need?)
grpWhoGo = {}
grpWhoGo[0] = 0
-- don't set morale/leadership/retreat
grpMorale = {}
grpMorale[0] = 90
-- leadership value
grpLeadership = {}
grpLeadership[0] = 0
-- retreat to base 1 assembly
grpRetreatXY = {}
grpRetreatXY[0] = 0
-- index in coords/sectors array (depends on grpType)
grpPosStart = {}
grpPosStart[0] = 3
-- Minimum index in coords array
grpPosMin = {}
grpPosMin[0] = 0
-- Maximum index in coords array
grpPosMax = {}
grpPosMax[0] = 4
-- Step increase for next 'waypoint'
grpPosStep = {}
grpPosStep[0] = 1
-- 0 = stop, 1 = loop, 2 = pingpong, 3 = random thru waypoints
grpPosType = {}
grpPosType[0] = 3
-- index factory to reinforce group. -1 = any factory.
grpFactory = {}
grpFactory[0] = 1
-- ideal size. If less than this factory will reinforce
grpIdealSize = {}
grpIdealSize[0] = 6

-- East Cyborgs
-- 0 = Ambush/Patrol, 1 = Defence, 2 = Scout, 3 = Attack...
grpType[1] = 0
-- player number (NP)
grpPlayer[1] = 0
-- index in regions array
grpRegion[1] = 1
-- 10mins time trigger (always make >= 0 for defence forces)
grpTimeGo[1] = 60
-- gamma base region for trigger (assume WhoGo = 0)
grpRegionGo[1] = 2
-- player number to cross trigger region (may not need?)
grpWhoGo[1] = 0
-- very timid! morale = 1%
grpMorale[1] = 90
-- leadership value
grpLeadership[1] = 0
-- retreat (index in coords array) base1 assembly
grpRetreatXY[1] = 0
-- index in sectors array (depends on grpType)
grpPosStart[1] = 0
-- Minimum index in coords array
grpPosMin[1] = 0
-- Maximum index in coords array
grpPosMax[1] = 4
-- Step increase for next 'waypoint'
grpPosStep[1] = 1
-- 0 = stop, 1 = loop, 2 = pingpong, 3 = random thru waypoints
grpPosType[1] = 2
-- index structure to reinforce group. -1 = any factory.
grpFactory[1] = 2
-- ideal size. If less than this factory will reinforce
grpIdealSize[1] = 10

-- hover Attackers
-- 0 = Ambush/Patrol, 1 = Defence, 2 = Scout, 3 = Attack...
grpType[2] = 3
-- player number (NP)
grpPlayer[2] = 0
-- index in regions array
grpRegion[2] = -1
-- 15mins time trigger (always make >= 0 for defence forces)
grpTimeGo[2] = 90
-- no region. index in regions array as trigger
grpRegionGo[2] = 2
-- player number to cross trigger region (may not need?)
grpWhoGo[2] = 0
-- morale = 25%
grpMorale[2] = 90
-- leadership value = 75%
grpLeadership[2] = 0
-- retreat (index in SECTORs array) base2 assembly
grpRetreatXY[2] = 0
-- index in coords array (depends on grpType)
grpPosStart[2] = 0
-- Minimum index in coords array
grpPosMin[2] = 0
-- Maximum index in coords array
grpPosMax[2] = 11
-- Step increase for next 'waypoint'
grpPosStep[2] = 1
-- 0 = stop, 1 = loop, 2 = pingpong, 3 = random thru waypoints
grpPosType[2] = 2
-- index factory to reinforce group. -1 = any factory.
grpFactory[2] = 0
-- ideal size. If less than this factory will reinforce
grpIdealSize[2] = 10

-- Main base defenders (for overspill)
-- 0 = Ambush/Patrol, 1 = Defence, 2 = Scout, 3 = Attack...
grpType[3] = 1
-- player number (NP)
grpPlayer[3] = -1
-- index in regions array
grpRegion[3] = -1
-- 10s time trigger (always make >= 0 for defence forces)
grpTimeGo[3] = 0
-- no region. index in regions array as trigger
grpRegionGo[3] = 5
-- player number to cross trigger region (may not need?)
grpWhoGo[3] = 0
-- pretty timid! morale = 25%
grpMorale[3] = 90
-- leadership value = 0%
grpLeadership[3] = 50
-- retreat (index in coords array) base 2 assembly
grpRetreatXY[3] = 1
-- index in coords array (depends on grpType)
grpPosStart[3] = 0
-- Minimum index in coords array
grpPosMin[3] = 0
-- Maximum index in coords array
grpPosMax[3] = 1
-- Step increase for next 'waypoint'
grpPosStep[3] = 1
-- 0 = stop, 1 = loop, 2 = pingpong, 3 = random thru waypoints
grpPosType[3] = 1
-- index factory to reinforce group. -1 = any factory.
grpFactory[3] = -1
-- ideal size. If less than this factory will reinforce
grpIdealSize[3] = 20


-- Factories
-- MAX = 10
numFactories = 3

-- South base Heavy factory
-- index to structures
factID = {}
factID[0] = 0
-- index to assembly point. -1 for don't set
factAssXY = {}
factAssXY[0] = -1
-- 15mindelay before starting production in 10s
factTimeGo = {}
factTimeGo[0] = 90
-- gamma base region for trigger (assume WhoGo = 0)
factRegionGo = {}
factRegionGo[0] = 2
-- index to starting template
factTempMin = {}
factTempMin[0] = 3
-- index to maximum template
factTempMax = {}
factTempMax[0] = 6
-- 7mins .Time in 10s for factory to try to produce again
factEvery = {}
factEvery[0] = 42

-- North base cyborg factory
-- index to structures
factID[1] = 1
-- index to assembly point. -1 for don't set
factAssXY[1] = -1
-- 5min delay before starting production in 10s
factTimeGo[1] = 30
-- gamma base region for trigger (assume WhoGo = 0)
factRegionGo[1] = 2
-- index to starting template
factTempMin[1] = 0
-- index to maximum template
factTempMax[1] = 2
-- 3mins .Time in 10s for factory to try to produce again
factEvery[1] = 18

-- South Base cyborg factory
-- index to structures
factID[2] = 3
-- index to assembly point. -1 for don't set
factAssXY[2] = -1
-- 10min delay before starting production in 10s
factTimeGo[2] = 60
-- gamma base region for trigger (assume WhoGo = 0)
factRegionGo[2] = 2
-- index to starting template
factTempMin[2] = 0
-- index to maximum template
factTempMax[2] = 2
-- 5mins .Time in 10s for factory to try to produce again
factEvery[2] = 30

-- 'Globals'
-- These should be same in each file, but may need slight alterations
-- player's player number
player = 0
crate = "Crate"
-- 171				//range to artifact about 1.5 tiles
artRange = 200
-- range to objective 5 Tiles
objectiveRange = 640
-- range to waypoint 2ish tiles
wayRange = 300
-- range for target spotting
targetRange = 768
-- maximum number of targets to store for each enemy
targetMax = 4
-- mission failed
lostSnd = "pcv470.ogg"
-- Base Under Attack
attackSnd1 = "pcv337.ogg"
-- artifact sounds
artSnd1 = "pcv351.ogg"
artSnd2 = "pcv352.ogg"
-- for enemy transports
transporter = "Transporter"

-- base WAVs. MAX = 5
-- Enemy Base Detected
baseSnd = {}
baseSnd[0] = "pcv379.ogg"
-- Enemy Base Detected
baseSnd[1] = "pcv379.ogg"
-- Enemy Base Detected
baseSnd[2] = "pcv379.ogg"
-- Enemy base eradicated
baseSnd[3] = "pcv394.ogg"

--run the code
dofile('genexp_logic.lua')
