-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "cam3daynight.slo"

-- cam3disk.vlo
-- Weather and day/night VLO for Cam3
-- set nighttime
-- change to a different CD

-- night time colour for fog ROCKIES
Rstart = 18
Gstart = 23
Bstart = 24

-- night time colour for fog
Rend = 18
Gend = 23
Bend = 24

-- number of seconds for change
Steps = 1
-- change back to CD#1
disk = 1

--run the code
dofile('cam3daynight_logic.lua')
