-- Generated by wz2lua (implementation file)
version(0) --- version of the script API this script is written for

function start()
	if campaign > 0 then
		setCampaignNumber(campaign)
	end
end
callbackEvent(start, CALL_GAMEINIT)


---------- stubs ----------

if setCampaignNumber == nil then setCampaignNumber = function() print("stub: setCampaignNumber"); return 0 end end
