-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "VTOLS.slo"

-- VLO  file for VTOLS with factory production

-- VTOL3-1.VLO

-- don't add any pads but setup the pad player
padPlayer = 3
-- MAX = 5
numPads = 0

-- vtol groups - MAX 4
numGroups = 2

-- place to put VTOLS
groupX = {}
groupX[0] = 192
groupY = {}
groupY[0] = 192
-- number of droids in group
VTOLsize = {}
VTOLsize[0] = 2
templates = {}
templates[0] = "NX-L-Missile-A-T-VTOL"
-- 0 - droid, 1 - structure
targetObjType = {}
targetObjType[0] = 0
-- 5mins (*10secs)
startTime = {}
startTime[0] = 30
-- 6mins (*10secs)
everyTime = {}
everyTime[0] = 36

-- place to put VTOLS
groupX[1] = 192
groupY[1] = 192
-- number of droids in group
VTOLsize[1] = 3
templates[1] = "NX-M-Bomb4-VTOL"
-- 0 - droid, 1 - structure
targetObjType[1] = 1
-- 7.5mins	(*10secs)
startTime[1] = 45
-- 9mins	(*10secs)
everyTime[1] = 54

-- HQ when destroyed stops VTOLS
HQbuilding = 680

vanishX = 15
vanishY = 1

-- preferred targets (max 4 each struc/droid)
numPrefStruc = 4
-- Sensor
prefStruc = {}
prefStruc[0] = 2048
-- RearmPad
prefStruc[1] = 1024
-- IDF
prefStruc[2] = 16384
-- Repair
prefStruc[3] = 64


numPrefDroid = 2
-- sensor
prefDroid = {}
prefDroid[0] = 2
-- IDFS
prefDroid[1] = 64

--run the code
dofile('vtols_logic.lua')
