-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "vtols.slo"




-- don't add any pads but setup the pad player
padPlayer = 3
-- MAX = 5
numPads = 0

-- set up the no vis targetting
player = 0
noVisTargetting = true

-- vtol groups - MAX 4
numGroups = 4

-- place to put VTOLS
groupX = {}
groupX[0] = 576
groupY = {}
groupY[0] = 32320
-- number of droids in group
VTOLsize = {}
VTOLsize[0] = 2
templates = {}
templates[0] = "NX-L-PulseLas-VTOL"
-- 0 - droid, 1 - structure
targetObjType = {}
targetObjType[0] = 0
-- 5min	(*10secs)
startTime = {}
startTime[0] = 30
-- 8mins(*10secs)
everyTime = {}
everyTime[0] = 48

-- place to put VTOLS
groupX[1] = 8000
groupY[1] = 28864
-- number of droids in group
VTOLsize[1] = 5
templates[1] = "NX-M-Bomb2-VTOL"
-- 0 - droid, 1 - structure
targetObjType[1] = 1
-- 10min	(*10secs)
startTime[1] = 60
-- 9min	(*10secs)
everyTime[1] = 54

-- place to put VTOLS
groupX[2] = 576
groupY[2] = 32320
-- number of droids in group
VTOLsize[2] = 5
templates[2] = "NX-M-Bomb2-VTOL"
-- 0 - droid, 1 - structure
targetObjType[2] = 1
-- 20min	(*10secs)
startTime[2] = 120
-- 8mins(*10secs)
everyTime[2] = 48

-- place to put VTOLS
groupX[3] = 8000
groupY[3] = 28864
-- number of droids in group
VTOLsize[3] = 2
templates[3] = "NX-L-PulseLas-VTOL"
-- 0 - droid, 1 - structure
targetObjType[3] = 0
-- 30min	(*10secs)
startTime[3] = 180
-- 8mins(*10secs)
everyTime[3] = 48

-- HQbuilding	STRUCTUREID	1180			//HQ when destroyed stops VTOLS
-- don't use an ID for stopping VTOLS
dontStopFlag = true

vanishX = 22
vanishY = 253

-- preferred targets (max 4 each struc/droid)
numPrefStruc = 3
-- Sensor
prefStruc = {}
prefStruc[0] = 2048
-- IDF structures
prefStruc[1] = 16384
-- Research facs
prefStruc[2] = 32


numPrefDroid = 2
-- sensor
prefDroid = {}
prefDroid[0] = 2
-- cyborgs
prefDroid[1] = 16384

--run the code
dofile('vtols_logic.lua')
