-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "VTOLS2.slo"

-- VLO  file for VTOLS with factory production

-- VTOL2C.VLO

padPlayer = 2

-- vtol groups - MAX 4
numGroups = 2

-- defines start group area to add
groupX1 = {}
groupX1[0] = 2112
groupY1 = {}
groupY1[0] = 1344
groupX2 = {}
groupX2[0] = 2368
groupY2 = {}
groupY2[0] = 2112
-- number of droids in group
VTOLsize = {}
VTOLsize[0] = 4
templates = {}
templates[0] = "CO-M-Bomb2-VTOL"
-- 0 - droid, 1 - structure
targetObjType = {}
targetObjType[0] = 1
groupFactory = {}
groupFactory[0] = getStructureByID(4679)
-- 10sec	(*10secs)
startTime = {}
startTime[0] = 1
-- 3mins (*10secs)
everyTime = {}
everyTime[0] = 18

-- defines start group area to add
groupX1[1] = 2112
groupY1[1] = 2112
groupX2[1] = 2368
groupY2[1] = 2624
-- number of droids in group
VTOLsize[1] = 3
templates[1] = "CO-L-RotMG-VTOL"
-- 0 - droid, 1 - structure
targetObjType[1] = 0
groupFactory[1] = getStructureByID(4680)
-- 20sec	(*10secs)
startTime[1] = 2
-- 3mins	(*10secs)
everyTime[1] = 18

-- preferred targets (max 4 each struc/droid)
numPrefStruc = 1
-- HQ
prefStruc = {}
prefStruc[0] = 1


numPrefDroid = 0

--run the code
dofile('vtols2_logic.lua')
