contact_links:
  - name: 💬 Official Discord and Webchat
    url: https://wz2100.net/webchat/
    about: Chat with members of the player community, get help with playing the game, and ask the developers questions!
