top_srcdir=../../..
top_builddir=$(top_srcdir)

CPPFLAGS:=-DSTATICLIB $(CPPFLAGS)

include $(top_srcdir)/makerules/common.mk

SRC= \
	miniwget.c \
	minixml.c \
	igd_desc_parse.c \
	minisoap.c \
	miniupnpc.c \
	upnpreplyparse.c \
	upnpcommands.c \
	minissdpc.c \
	upnperrors.c

LIB=miniupnpc

include $(top_srcdir)/makerules/lib.mk