-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "start.slo"

-- start.vlo
-- to start player stuff off

-- player's player number
player = 0
startPow = 1000
numTechs = 5
startTech = {}
startTech[0] = "R-Vehicle-Body01"
startTech[1] = "R-Sys-Spade1Mk1"
startTech[2] = "R-Vehicle-Prop-Wheels"
startTech[3] = "R-Wpn-MG1Mk1"
startTech[4] = "R-Wpn-MG-Damage03"
-- req'd for 1st level
mg = getWeapon("MG1Mk1")

--run the code
dofile('start_logic.lua')
