-- Generated by wz2lua (implementation file)
version(0) --- version of the script API this script is written for
-- req'd for start level
count = 0
count2 = 0

-- Initialisation
function start()
	count2 = 0
	while count2 < numTechs do
		completeResearch(startTech[count2], player)
		count2 = count2 + 1
	end
	-- set power level
	setPowerLevel(startPow, player)
end
callbackEvent(start, CALL_GAMEINIT)


---------- stubs ----------

if completeResearch == nil then completeResearch = function() print("stub: completeResearch"); return 0 end end
if setPowerLevel == nil then setPowerLevel = function() print("stub: setPowerLevel"); return 0 end end
