top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

SRC= \
	bar.cpp \
	button.cpp \
	editbox.cpp \
	form.cpp \
	label.cpp \
	scrap.cpp \
	slider.cpp \
	tip.cpp \
	widget.cpp

LIB=widget

include $(top_srcdir)/makerules/lib.mk
