top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

SRC= \
	bar.c \
	button.c \
	editbox.c \
	form.c \
	label.c \
	scrap.c \
	slider.c \
	tip.c \
	widget.c

LIB=widget

include $(top_srcdir)/makerules/lib.mk
