.\" Forwarded to http://developer.wz2100.net/ticket/357
.TH WARZONE2100 6 "2007-04-29"
.SH NAME
warzone2100 \- 3D real time strategy game
.SH SYNOPSIS
.B warzone2100
.RI [ OPTION ]...
.RI [ ARGS ]...
.SH DESCRIPTION
This manual page documents briefly the
.B warzone2100
commands.
.PP
.B warzone2100
is a 3D science fiction real time strategy game.
.SH OPTIONS
.TP
.B \-\-cheat
Run in cheat mode.
.TP
\fB\-\-datadir=\fP\fIDIR\fP
Set default datadir to \fIDIR\fP.
.TP
\fB\-\-debug=\fP\fIFLAG\fP
Show debug for \fIFLAG\fP. This parameter can be \fI\-\-debug=all\fP to show all debug.
.TP
\fB\-\-debugfile=\fP\fIFILE\fP
Log debug output in \fIFILE\fP.
.TP
.B \-\-fullscreen
Play in fullscreen mode.
.TP
.B \-\-help
Show help and exit.
.TP
\fB\-\-mod=\fP\fIMOD\fP
Enable global mod \fIMOD\fP.
.TP
\fB\-\-mod\_ca=\fP\fIMOD\fP
Enable campaign only mod \fIMOD\fP.
.TP
\fB\-\-mod\_mp=\fP\fIMOD\fP
Enable multiplay only mod \fIMOD\fP.
.TP
\fB\-\-savegame=\fP\fINAME\fP
Load a saved game \fINAME\fP.
.TP
.B \-\-window
Play in windowed mode.
.TP
.B \-\-version
Output version info and exit.
.TP
\fB\-\-resolution=\fP\fIWIDTH\fPx\fIHEIGHT\fP
Run at
.I WIDTH
times
.I HEIGHT
screen resolution. This needs to be a resolution supported by your X
server.
.TP
.B \-\-(no)shadows
Toggle the shadows.
.TP
.B \-\-(no)sound
Toggle the sound.
.PP
The fullscreen/window, resolution, sound, and shadows settings are stored,
so they only need to be specified once, or when you want to change them.
.SH EXAMPLES
.TP
.I warzone2100 \-\-fullscreen \-\-resolution=800x600
Run in full screen at 800x600 screen resolution.
.TP
.I warzone2100 \-\-window \-\-resolution=800x600
Run in a window at 800x600 screen resolution.
.TP
.I warzone2100
Run using the parameters specified last time (not including debug parameters).
.SH AUTHORS
See the
.I copyright
file included in the package.
.PP
This manual page was written by Linas Zvirblis <0x0007@gmail.com>
for the Debian project (but may be used by others).
