MAKERULES=../makerules
include $(MAKERULES)/configure.mk

SETUPFILE=warzone2100-$(VERSION).exe

ifeq ($(strip $(PLATFORM)),windows)
all: $(SETUPFILE)
endif

$(SETUPFILE): warzone2100.nsi ../src/warzone2100.exe ../data/warzone.wz ../data/mp.wz ../data/grim.wz
	$(MAKENSIS) "/DVERSION=$(VERSION)" "/DVERSIONNUM=$(INSTALLER_VERSION)" "/DLIBDIR=$(DEVDIR)\lib" $<

clean:
	$(RM) $(SETUPFILE)
