MAKERULES=../makerules
include $(MAKERULES)/configure.mk

ifeq ($(strip $(PLATFORM)),windows)

SETUPFILE=warzone2100-$(VERSION).exe

all: $(SETUPFILE)

$(SETUPFILE): warzone2100.nsi ../src/warzone2100.exe ../data/warzone.wz ../data/mp.wz ../data/grim.wz
	makensis "/DVERSION=$(VERSION)" "/DVERSIONNUM=$(VERSION)" "/DLIBDIR=$(DEVDIR)\lib" "/DSRCDIR=..\src" "/DDATADIR=..\data" "/DMISCDIR=.." $<

clean:
	$(RM) $(SETUPFILE)

endif
