MAKERULES=../makerules
include $(MAKERULES)/configure.mk

ifeq ($(strip $(PLATFORM)),windows)

SETUPFILE=Warzone\ 2100.exe

all: $(SETUPFILE)

$(SETUPFILE): warzone2100.nsi ../src/warzone2100.exe ../data/warzone.wz ../data/mp.wz ../data/grim.wz
	makensis "/DDEVDIR=$(DEVDIR)" "/DOUTFILE=$@" $<

clean:
	$(RM) $(SETUPFILE)

endif
