SRC_FILES=	ai.c \
		astar.c \
		action.c \
		advvis.c \
		atmos.c \
		bridge.c \
		buildpos.c \
		cdspan.c \
		cheat.c \
		cluster.c \
		cmddroid.c \
		combat.c \
		component.c \
		console.c \
		data.c \
		design.c \
		difficulty.c \
		disp2d.c \
		display.c \
		droid.c \
		e3demo.c \
		edit2d.c \
		edit3d.c \
		effects.c \
		environ.c \
		fpath.c \
		feature.c \
		findpath.c \
		formation.c \
		frontend.c \
		gateway.c \
		gatewayroute.c \
		gatewaysup.c \
		geometry.c \
		group.c \
		hci.c \
		init.c \
		intdisplay.c \
		intimage.c \
		intorder.c \
		intelmap.c \
		keybind.c \
		keymap.c \
		level_l.c \
		levels.c \
		lighting.c \
		loop.c \
		map.c \
		mapdisplay.c \
		mapgrid.c \
		mechanics.c \
		message.c \
		miscimd.c \
		move.c \
		multiint.c \
		multimenu.c \
		multiopt.c \
		multisync.c \
		multibot.c \
		multistat.c \
		objmem.c \
		objects.c \
		optimisepath.c \
		order.c \
		player.c \
		powercrypt.c \
		radar.c \
		raycast.c \
		research.c \
		scores.c \
		scriptai.c \
		scriptcb.c \
		scriptextern.c \
		scriptfuncs.c \
		scriptobj.c \
		scripttabs.c \
		scriptvals.c \
		scriptvals_l.c \
		scriptvals_y.c \
		selection.c \
		stats.c \
		text.c \
		texture.c \
		transporter.c \
		visibility.c \
		warcam.c \
		water.c \
		wrappers.c \
		ani.c \
		arrow.c \
		aud.c \
		audio_id.c \
		bucket3d.c \
		clparse.c \
		configuration.c \
		csnap.c \
		display3d.c \
		drive.c \
		function.c \
		game.c \
		ingameop.c \
		keyedit.c \
		loadsave.c \
		main.c \
		mission.c \
		mplayer.c \
		multigifts.c \
		multijoin.c \
		multilimit.c \
		multiplay.c \
		multistruct.c \
		oprint.c \
		power.c \
		projectile.c \
		readfiles.c \
		seqdisp.c \
		structure.c \
		target.c \
		warzoneconfig.c

EXE=		warzone

LIBS=		framework \
		gamelib \
		netplay \
		script \
		sequence \
		sound \
		widget

EXT_LIBS=	mad vorbisfile vorbis ogg $(OPENAL_LIB) SDL_net

ifeq ($(GFX), software)
LIBS+=ivis02
else
LIBS+=ivis_opengl
EXT_LIBS+=$(OPENGL_LIB) jpeg
endif
LIBS+=ivis_common

MAKERULES=../makerules
include $(MAKERULES)/exe.mk

# On every build, record the working copy revision string in revision.h
# if svnversion is not installed, it will be just an empty string.
# Also delete frontend.o so it is remade unconditionally to have an
# up-to-date revision number.
STUPID_TRICK := $(shell rm -rf frontend.o)
REWRITE_REVISION_H1 := $(shell echo -n '\#define SVN_REVISION "Revision ' > revision.h)
REWRITE_REVISION_H2 := $(shell svnversion -n . >> revision.h)
REWRITE_REVISION_H3 := $(shell echo '"' >> revision.h)
