#!/bin/sh

source __BUILD_CONFIG

if [[ "x$1" = "xdebug" ]] ; then
	CONF_EXTRA_FLAGS="--enable-debug"
elif [[ "x$1" = "xinstaller" ]] ; then
	CONF_EXTRA_FLAGS="--enable-data --enable-installer
		--with-installer-extdir=\"${PREFIX}/bin\" --with-installer-version=${INSTALLER_VERSION}"
fi

./autogen.sh || exit 1
./configure --target=${CROSSCOMPILETARGET} --host=${CROSSCOMPILETARGET} --enable-static --disable-shared \
    --prefix="${PREFIX}" \
	${CONF_EXTRA_FLAGS} \
    CFLAGS="${CFLAGS}" \
    CPPFLAGS="${CPPFLAGS}" \
    LDFLAGS="${LDFLAGS}" || exit 1
make -j3 || exit 1
