#!/bin/sh
if [ -f __BUILD_CONFIG.USER ]; then
    . __BUILD_CONFIG.USER
fi

if test "x$PREFIX" = "x"; then
    PREFIX="${HOME}/svn/warzone/devpkg-2.1"
fi

export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"
PATH="${PREFIX}/bin:${PATH}"

__BOTHFLAGS="-pipe -m32 -march=i686 -O2 -g ${CFLAGS}"
CFLAGS="${__BOTHFLAGS} ${CFLAGS}"
CXXFLAGS="${__BOTHFLAGS} ${CXXFLAGS}"
CPPFLAGS="${CPPFLAGS} -I${PREFIX}/include"
LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"

if test "x$INSTALLER_VERSION" = "x"; then
	INSTALLER_VERSION="2.0.8.0"
fi

if test "x$CROSSCOMPILETARGET" = "x"; then
    CROSSCOMPILETARGET=mingw32
fi
