del ..\lib\framework\resource_lexer.lex.c
del ..\lib\framework\resource_parser.tab.c
del ..\lib\framework\resource_parser.tab.h
del ..\lib\framework\strres_lexer.lex.c
del ..\lib\framework\strres_parser.tab.c
del ..\lib\framework\strres_parser.tab.h
del ..\lib\gamelib\audp_lexer.lex.c
del ..\lib\gamelib\audp_parser.tab.c
del ..\lib\gamelib\audp_parser.tab.h
del ..\lib\script\chat_lexer.lex.c
del ..\lib\script\chat_parser.tab.c
del ..\lib\script\chat_parser.tab.h
del ..\lib\script\script_lexer.lex.c
del ..\lib\script\script_parser.tab.c
del ..\lib\script\script_parser.tab.h
del ..\src\autorevision.h
del ..\src\level_lexer.lex.c
del ..\src\message_lexer.lex.c
del ..\src\message_parser.tab.c
del ..\src\message_parser.tab.h
del ..\src\scriptvals_lexer.lex.c
del ..\src\scriptvals_parser.tab.c
del ..\src\scriptvals_parser.tab.h
