del ..\lib\framework\resource_lexer.cpp
del ..\lib\framework\resource_parser.cpp
del ..\lib\framework\resource_parser.hpp
del ..\lib\framework\strres_lexer.cpp
del ..\lib\framework\strres_parser.cpp
del ..\lib\framework\strres_parser.hpp
del ..\lib\gamelib\audp_lexer.cpp
del ..\lib\gamelib\audp_parser.cpp
del ..\lib\gamelib\audp_parser.hpp
del ..\lib\script\chat_lexer.cpp
del ..\lib\script\chat_parser.cpp
del ..\lib\script\chat_parser.hpp
del ..\lib\script\script_lexer.cpp
del ..\lib\script\script_parser.cpp
del ..\lib\script\script_parser.hpp
del ..\src\autorevision.h
del ..\src\level_lexer.cpp
del ..\src\message_lexer.cpp
del ..\src\message_parser.cpp
del ..\src\message_parser.hpp
del ..\src\scriptvals_lexer.cpp
del ..\src\scriptvals_parser.cpp
del ..\src\scriptvals_parser.hpp
