SRC_FILES=	netaudio_stub.c \
		netcrypt.c \
		netjoin_stub.c \
		netlobby_stub.c \
		netlog.c \
		netplay.c \
		netusers_stub.c

LIBS=framework

LIB=netplay

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

