top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

SRC= \
	netjoin_stub.cpp \
	netlog.cpp \
	netplay.cpp \
	netqueue.cpp \
	nettypes.cpp \
	netsocket.cpp

LIB=netplay

include $(top_srcdir)/makerules/lib.mk
include $(top_srcdir)/makerules/submake.mk
