-- Generated by wz2lua (implementation file)
version(0) --- version of the script API this script is written for
-- keeps track of current factory
n = 0

-- Factory values
-- must be >= numFacts

-- Build Templates
-- must be >= numFacts


-- Triggers
-- new build every 10 seconds


-- Events
function startup()
	setPowerLevel(power, player)
	while n < numFacts do
		setAssemblyPoint(fact[n], assX[n], assY[n])
		n = n + 1
	end
	n = 0
end
delayedEvent(startup, 0)

-- build list for all factories (n controls which!)
-- try building every 10 seconds
function factEvnt()
	if not (destroyed(factID[n])) then
		if structureIdle(fact[n]) then
			buildDroid(build[n], fact[n], player, 1)
		end
	end
	n = n + 1
	if n >= numFacts then
		n = 0
	end
end
repeatingEvent(factEvnt, 10.0)


---------- stubs ----------

if buildingDestroyed == nil then buildingDestroyed = function() print("stub: buildingDestroyed"); return 0 end end
if buildDroid == nil then buildDroid = function() print("stub: buildDroid"); return 0 end end
if structureIdle == nil then structureIdle = function() print("stub: structureIdle"); return 0 end end
if setAssemblyPoint == nil then setAssemblyPoint = function() print("stub: setAssemblyPoint"); return 0 end end
if setPowerLevel == nil then setPowerLevel = function() print("stub: setPowerLevel"); return 0 end end
