//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by max2pie.rc
//
#define IDS_PIEEXP                      1
#define IDS_NO_MATERIAL                 2
#define IDS_ANNETTE_BELL                40222
#define IDS_COPYRIGHT_PUMPKIN           40223
#define IDS_SCENEEXPORT                 40231
#define IDS_NODATATOEXPORT              40233
#define IDS_CANTCREATE                  40234
#define IDS_WRITEERROR                  40235
#define IDS_PUMPKIN                     40236
#define IDS_PIEEXPORTDLL                40237
#define IDS_PUMPKINPIEFILE              40238
#define IDS_VERTEXERROR                 40239
#define IDS_TEXTBITMAPERROR             40240
#define IDS_INCORRECT_BIT               40242
#define IDS_NOBITMAP                    40243
#define IDS_NEGATIVE_COORD              40244
#define IDS_ROTATION_ERROR              40245
#define IDS_POSROTSCALE_TRACK           40251
#define IDS_ANIM_TRANS                  40251
#define IDS_HELPERERROR                 40252
#define IDS_ANIM_OBJECT                 40253
#define IDS_BADUSERSTRING               40254
#define IDS_NOANIMDATAPRESENT           40255
#define IDS_ANIMDATAPRESENT             40256
#define IDS_ANIM_FRAMES                 40257
#define IDS_NO_TEXTURE_VERTS            40258

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
