include $(top_srcdir)/makerules/common.mk

# Hacks to build for compiling system, not for target
CC:=g++
CXX:=g++
CPPFLAGS:=$(subst -DWIN32,,$(CPPFLAGS))
CFLAGS:=$(subst -mwindows,,$(CFLAGS))
CXXFLAGS:=$(subst -mwindows,,$(CXXFLAGS))
LDFLAGS:=
EXEEXT=

SRC=autorevision.cpp

EXE=autorevision

include $(top_srcdir)/makerules/exe.mk

.PHONY: all all-local clean clean-local

all: all-local

all-local: $(EXE)$(EXEEXT)
	$(EXE)$(EXEEXT) +cstr -v $(subst /,\\,$(top_srcdir)) $(subst /,\\,$(top_builddir)/src/autorevision.h)

clean-local:
	-$(RM_F) $(subst /,\\,$(top_builddir)/src/autorevision.h)

clean: clean-local
	$(RM_F) $(DEPS) $(EXE)$(EXEEXT)
