MAKERULES=../makerules
include $(MAKERULES)/configure.mk

BASELIST = anims audio components effects features \
	gamedesc.lev images locale messages misc multiplay novideo.rpl palette.bin \
	script sequenceaudio stats structs texpages wrf
PATCHLIST = addon.lev anims components effects \
	messages multiplay stats structs wrf
GRIMLIST = components structs texpages wrf

BASEARCHIVE=warzone.wz
PATCHARCHIVE=mp.wz
GRIMARCHIVE=grim.wz

all:
ifdef DATA
all: $(BASEARCHIVE) $(PATCHARCHIVE) $(GRIMARCHIVE)
endif

$(BASEARCHIVE): $(BASELIST)
	zip -ru0 $@ $(BASELIST) -x *svn*
	zip -T $@

$(PATCHARCHIVE): $(PATCHLIST:%=mp/%)
	cd mp && zip -ru0 ../$@ $(PATCHLIST) -x *svn*
	zip -T $@

$(GRIMARCHIVE): $(GRIMLIST:%=grim/%)
	cd grim && zip -ru0 ../$@ $(GRIMLIST) -x *svn*
	zip -T $@

clean:
	$(RMF) $(BASEARCHIVE)
	$(RMF) $(PATCHARCHIVE)
	$(RMF) $(GRIMARCHIVE)
