include $(top_srcdir)/makerules/common.mk

SUBDIRS=mods

BASELIST=anims audio components effects features tagdefinitions \
	gamedesc.lev images messages misc multiplay music novideo.rpl script \
	sequenceaudio stats stats-sql structs texpages wrf
PATCHLIST=addon.lev anims components effects \
	messages multiplay stats structs wrf

BASEARCHIVE=base.wz
PATCHARCHIVE=mp.wz

CLEANFILES=$(BASEARCHIVE) $(PATCHARCHIVE)

include $(top_srcdir)/makerules/submake.mk

.PHONY: all clean $(BASEARCHIVE) $(PATCHARCHIVE) $(SUBDIRS)

all:
ifdef DATA
all: $(BASEARCHIVE) $(PATCHARCHIVE) $(SUBDIRS)
endif

stamp:
	touch stamp

$(BASEARCHIVE): $(basename $(BASEARCHIVE)) stamp $(patsubst %,$(basename $(BASEARCHIVE))/%,$(BASELIST))
	(cd $< && zip -ru0 $@ $(filter-out stamp,$(filter-out $<,$(^:$</%=%))) -x '*svn*' || [ $$? -eq 12 ] && true) # zip returns 12 on "nothing to do"
	zip -T $@
	$(RM_F) stamp

$(PATCHARCHIVE): $(basename $(BASEARCHIVE)) stamp $(patsubst %,$(basename $(PATCHARCHIVE))/%,$(PATCHLIST))
	(cd $< && zip -ru0 $@ $(filter-out stamp,$(filter-out $<,$(^:$</%=%))) -x '*svn*' || [ $$? -eq 12 ] && true) # zip returns 12 on "nothing to do"
	zip -T $@
	$(RM_F) stamp

clean: $(SUBDIRS)
	$(RM_F) $(BASEARCHIVE)
	$(RM_F) $(PATCHARCHIVE)
