SUBDIRS=mods

MAKERULES=../makerules
include $(MAKERULES)/configure.mk

BASELIST = anims audio components effects features tagdefinitions \
	gamedesc.lev images messages misc multiplay novideo.rpl \
	script sequenceaudio stats stats-sql structs texpages wrf
PATCHLIST = addon.lev anims components effects \
	messages multiplay stats structs wrf

BASEARCHIVE=warzone.wz
PATCHARCHIVE=mp.wz

all:
ifdef DATA
all: $(BASEARCHIVE) $(PATCHARCHIVE) $(SUBDIRS)
endif

$(SUBDIRS):
	$(MAKE) -f Makefile.raw -C $@ $(MAKECMDGOALS)

$(BASEARCHIVE): $(BASELIST)
	zip -ru0 $@ $(BASELIST) -x *svn*
	zip -T $@

$(PATCHARCHIVE): $(PATCHLIST:%=mp/%)
	cd mp && zip -ru0 ../$@ $(PATCHLIST) -x *svn*
	zip -T $@

clean: $(SUBDIRS)
	$(RMF) $(BASEARCHIVE)
	$(RMF) $(PATCHARCHIVE)

.PHONY: all clean $(SUBDIRS) $(BASEARCHIVE) $(PATCHARCHIVE)
