-- Generated by wz2lua (data file)
version(0) -- version of the script API this script is written for
-- slo: "tech.slo"

-- cam2tech.vlo
-- set up starting technology, templates etc. for player at the start of a campaign

numTechs = 26
player = 0
startTech = {}
startTech[0] = "R-Cyborg-Legs01"
startTech[1] = "R-Cyborg-Metals03"
startTech[2] = "R-Defense-WallUpgrade03"
startTech[3] = "R-Struc-Factory-Upgrade03"
startTech[4] = "R-Struc-Factory-Cyborg-Upgrade03"
startTech[5] = "R-Struc-Materials03"
startTech[6] = "R-Struc-Research-Upgrade03"
startTech[7] = "R-Struc-RprFac-Upgrade03"
startTech[8] = "R-Sys-Engineering01"
startTech[9] = "R-Sys-MobileRepairTurret01"
startTech[10] = "R-Wpn-Cannon-Damage03"
startTech[11] = "R-Wpn-Flamer-Damage03"
startTech[12] = "R-Wpn-Flamer-ROF01"
startTech[13] = "R-Wpn-MG-Damage04"
startTech[14] = "R-Wpn-MG-ROF01"
startTech[15] = "R-Wpn-Mortar-Damage03"
startTech[16] = "R-Wpn-Rocket-Accuracy02"
startTech[17] = "R-Wpn-Rocket-ROF03"
startTech[18] = "R-Wpn-RocketSlow-Accuracy02"
startTech[19] = "R-Wpn-RocketSlow-Damage03"
startTech[20] = "R-Vehicle-Engine03"
startTech[21] = "R-Vehicle-Metals03"
startTech[22] = "R-Wpn-AAGun03"
startTech[23] = "R-Defense-AASite-QuadMg1"
startTech[24] = "R-Sys-Sensor-Tower02"
-- needs to be researced to allow Ripple Rocket Emplacement
startTech[25] = "R-Defense-MRL"

numStructs = 26
startStruct = {}
startStruct[0] = "A0ComDroidControl"
startStruct[1] = "A0CommandCentre"
startStruct[2] = "A0CyborgFactory"
startStruct[3] = "A0FacMod1"
startStruct[4] = "A0HardcreteMk1CWall"
startStruct[5] = "A0HardcreteMk1Wall"
startStruct[6] = "A0LightFactory"
startStruct[7] = "A0PowerGenerator"
startStruct[8] = "A0PowMod1"
startStruct[9] = "A0RepairCentre3"
startStruct[10] = "A0ResearchFacility"
startStruct[11] = "A0ResearchModule1"
startStruct[12] = "A0ResourceExtractor"
startStruct[13] = "A0TankTrap"
startStruct[14] = "PillBox1"
startStruct[15] = "PillBox4"
startStruct[16] = "PillBox5"
startStruct[17] = "PillBox6"
startStruct[18] = "TankTrapC"
startStruct[19] = "WallTower01"
startStruct[20] = "WallTower03"
startStruct[21] = "WallTower04"
startStruct[22] = "WallTower06"
startStruct[23] = "AASite-QuadMg1"
startStruct[24] = "Emplacement-MortarPit01"
startStruct[25] = "Emplacement-MRL-pit"
-- startStruct	[23]	STRUCTURESTAT	"A0RepairCentre"
-- startStruct	[27]	STRUCTURESTAT	"GuardTower4"
-- startStruct	[28]	STRUCTURESTAT	"GuardTower5"
-- startStruct	[29]	STRUCTURESTAT	"GuardTower6"

numWeapons = 20
startWeapon = {}
startWeapon[0] = getWeapon("Cannon1Mk1")
startWeapon[1] = getWeapon("Cannon2A-TMk1")
startWeapon[2] = getWeapon("Cannon375mmMk1")
startWeapon[3] = getWeapon("Flame1Mk1")
startWeapon[4] = getWeapon("MG1Mk1")
startWeapon[5] = getWeapon("MG2Mk1")
startWeapon[6] = getWeapon("MG3Mk1")
startWeapon[7] = getWeapon("Mortar1Mk1")
startWeapon[8] = getWeapon("Mortar2Mk1")
startWeapon[9] = getWeapon("Rocket-BB")
startWeapon[10] = getWeapon("Rocket-LtA-T")
startWeapon[11] = getWeapon("Rocket-MRL")
startWeapon[12] = getWeapon("Rocket-Pod")
startWeapon[13] = getWeapon("Cannon1-VTOL")
startWeapon[14] = getWeapon("MG1-VTOL")
startWeapon[15] = getWeapon("MG2-VTOL")
startWeapon[16] = getWeapon("MG3-VTOL")
startWeapon[17] = getWeapon("Rocket-VTOL-LtA-T")
startWeapon[18] = getWeapon("Rocket-VTOL-Pod")
startWeapon[19] = getWeapon("Rocket-VTOL-BB")

numBodies = 10
startBody = {}
startBody[0] = "Body1REC"
startBody[1] = "Body5REC"
startBody[2] = "Body11ABT"
startBody[3] = "Body4ABT"
startBody[4] = "Body8MBT"
startBody[5] = "Body12SUP"
startBody[6] = "CyborgCannonGrd"
startBody[7] = "CyborgFlamerGrd"
startBody[8] = "CyborgChain1Ground"
startBody[9] = "CyborgRkt1Ground"

numProps = 4
startProp = {}
startProp[0] = "HalfTrack"
startProp[1] = "hover01"
startProp[2] = "tracked01"
startProp[3] = "wheeled01"

numConstructs = 1
startConstruct = {}
startConstruct[0] = "Spade1Mk1"

numSensors = 1
startSensor = {}
startSensor[0] = "SensorTurret1Mk1"

numECMs = 0
-- startECM	[0]	ECM		""

numRepairs = 0
-- startRepair	[0]	REPAIR		""

numBrains = 1
startBrain = {}
startBrain[0] = "CommandBrain01"

numResearch = 1
startResearch = {}
startResearch[0] = "R-Wpn-Cannon-Accuracy02"

--run the code
dofile('tech_logic.lua')
