-- Generated by wz2lua (implementation file)
version(0) --- version of the script API this script is written for

function initialisedEvent()
	setStructureLimits(factory, 30, 0)
	setStructureLimits(powerGen, 30, 0)
	setStructureLimits(research, 30, 0)
	setStructureLimits(comdroid, 1, 0)
	setStructureLimits(cybfac, 30, 0)
	setStructureLimits(repair, 30, 0)
	setStructureLimits(vtolfact, 30, 0)
	setStructureLimits(vtolpad, 100, 0)
	setStructureLimits(lassat, 1, 0)
end
delayedEvent(initialisedEvent, 0)


---------- stubs ----------

if setStructureLimits == nil then setStructureLimits = function() print("stub: setStructureLimits"); return 0 end end
