top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

# Due to the lexer's dependencies on the parser's header we need to compile the
# parsers first
PARSERS= \
	audp_parser.tab.c \
	audp_lexer.lex.c

SRC= \
	$(PARSERS) \
	anim.c \
	animobj.c \
	gtime.c \
	hashtable.c

LIB=gamelib

CLEANFILES=audp_parser.tab.h $(PARSERS)

include $(top_srcdir)/makerules/lib.mk
