SRC_FILES=	anim.c \
		animobj.c \
		audp_parser.c \
		audp_lexer.c \
		gtime.c \
		hashtabl.c \
		pqueue.c \
		ptrlist.c

LIBS=framework ivis_common sound

ifeq ($(GFX), software)
LIBS+=ivis02
else
LIBS+=ivis_opengl
endif

GENERATED_SRC=	resource_lexer.c \
		resource_parser.c \
		resource_parser.h

LIB=gamelib

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

audp_lexer.c: audp_lexer.l
	flex $(<)
	mv lex.audp_.c $@

audp_parser.c audp_parser.h: audp_parser.y
	bison audp_parser.y
	mv audp_parser.tab.c audp_parser.c
	mv audp_parser.tab.h audp_parser.h

