MAKERULES=../../makerules
include $(MAKERULES)/configure.mk

# Due to the lexer's dependencies on the parser's header we need to compile the
# parsers first
PARSERS= \
	audp_parser.tab.c \
	audp_lexer.lex.c

SRC= \
	anim.c \
	animobj.c \
	gtime.c \
	hashtabl.c

LIB=gamelib

include $(MAKERULES)/lib.mk
