top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

# Due to the lexer's dependencies on the parser's header we need to compile the
# parsers first
PARSERS= \
	audp_parser.tab.cpp \
	audp_lexer.lex.cpp

SRC= \
	$(PARSERS) \
	anim.cpp \
	animobj.cpp \
	gtime.cpp \
	hashtable.cpp

LIB=gamelib

CLEANFILES=audp_parser.tab.h $(PARSERS)

include $(top_srcdir)/makerules/lib.mk
