SRC_FILES=	anim.c \
		animobj.c \
		gtime.c \
		hashtabl.c \
		parser_l.c \
		parser_y.c \
		pqueue.c \
		ptrlist.c

LIBS=framework ivis02 sound

LIB=gamelib

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

