top_srcdir=../..
top_builddir=$(top_srcdir)

include $(top_srcdir)/makerules/common.mk

SRC= \
	audio.cpp \
	audio_id.cpp \
	cdaudio.cpp \
	oggvorbis.cpp \
	openal_error.cpp \
	openal_track.cpp \
	playlist.cpp \
	track.cpp

LIB=sound

include $(top_srcdir)/makerules/lib.mk
