include $(top_srcdir)/makerules/common.mk

SRC=audio.c \
	audio_id.c \
	cdaudio.c \
	oggvorbis.c \
	openal_track.c \
	openal_error.c \
	playlist.c \
	track.c

LIB=sound

include $(top_srcdir)/makerules/lib.mk
