include $(abs_top_srcdir)/makerules/configure.mk

SRC=audio.c \
	audio_id.c \
	cdaudio.c \
	oggvorbis.c \
	openal_track.c \
	openal_error.c \
	playlist.c \
	track.c

LIB=sound

include $(abs_top_srcdir)/makerules/lib.mk
