SRC_FILES=	netaudio_stub.c \
		netcrypt.c \
		netjoin_stub.c \
		netlobby_stub.c \
		netplay_stub.c \
		netprov_stub.c \
		netsupp_stub.c \
		netusers_stub.c

LIBS=framework

LIB=netplay

MAKERULES=../../makerules
include $(MAKERULES)/lib.mk

