name: Crowdin - Upload Sources

on: workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-master

jobs:
  crowdin-upload-sources:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: crowdin_sync
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: 'master'

      - name: Crowdin Action
        uses: crowdin/github-action@v2
        with:
          config: 'crowdin.yml'
          upload_sources: true
          upload_translations: false
          download_translations: false
          crowdin_branch_name: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
